##[[
  if not TICO.SHARED then
    cflags('-L '..TICO.L)

    cflags('-I '..TICO.I.include)
    cflags('-I '..TICO.I.external)

    linklib'tico_lib'
    linklib'glfw'
    linklib'gl3w'
    linklib'GL'
    linklib'lua'
    linklib'cimgui'
    linklib'dl'
    linklib'X11'
    linklib'pthread'
    linklib'stdc++'
  end

  cinclude'<tico.h>'
]]

local stbtt_fontinfo: type <cimport, nodecl> = @record{}
local cJSON: type <cimport, nodecl> = @record{}
local lua_State: type <cimport, nodecl> = @record{}
local LuaFunction: type <cimport, nodecl> = @function(*lua_State): cint
local map_base_t <cimport, nodecl> = @record{}
local ma_decoder <cimport, nodecl> = @record{}
local GLFWcursor <cimport, nodecl> = @record{}
local GLFWwindow <cimport, nodecl> = @record{}
local ImGuiWindowFlags_ <cimport, nodecl> = @record{}


local map_fieldtype_t: type <cimport, nodecl> = @record{}
local map_field_t: type <cimport, nodecl> = @record{}
local map_anim_t: type <cimport, nodecl> = @record{}
local map_plugin_t: type <cimport, nodecl> = @record{}
local map_deps_t: type <cimport, nodecl> = @record{}
local map_resource_t: type <cimport, nodecl> = @record{}
local map_resref_t: type <cimport, nodecl> = @record{}
local map_resplugin_t: type <cimport, nodecl> = @record{}
local map_editorplugin_t: type <cimport, nodecl> = @record{}
local map_editorwindow_t: type <cimport, nodecl> = @record{}
local map_object_t: type <cimport, nodecl> = @record{}
local map_void_t: type <cimport, nodecl> = @record{}
local map_str_t: type <cimport, nodecl> = @record{}
local map_int_t: type <cimport, nodecl> = @record{}
local map_char_t: type <cimport, nodecl> = @record{}
local map_float_t: type <cimport, nodecl> = @record{}
local map_double_t: type <cimport, nodecl> = @record{}
local vec_canvas_t: type <cimport, nodecl> = @record{}
local vec_void_t: type <cimport, nodecl> = @record{}
local vec_str_t: type <cimport, nodecl> = @record{}
local vec_int_t: type <cimport, nodecl> = @record{}
local vec_char_t: type <cimport, nodecl> = @record{}
local vec_float_t: type <cimport, nodecl> = @record{}
local vec_double_t: type <cimport, nodecl> = @record{}
local list_resdep_t: type <cimport, nodecl> = @record{}
local list_int_t: type <cimport, nodecl> = @record{}
local list_char_t: type <cimport, nodecl> = @record{}
local list_str_t: type <cimport, nodecl> = @record{}
local list_float_t: type <cimport, nodecl> = @record{}
local stack_canvas_t: type <cimport, nodecl> = @record{}
local stack_shader_t: type <cimport, nodecl> = @record{}
local stack_matrix_t: type <cimport, nodecl> = @record{}

global tico = @record{}

function tico.utils_generate_uuid(out: cstring, size: cint) <cimport'tico_utils_generate_uuid', nodecl> end
function tico.utils_get_ratio(w0: float32, h0: float32, w1: float32, h1: float32): float32 <cimport'tico_utils_get_ratio', nodecl> end
function tico.utils_hash(key: cstring): cint <cimport'tico_utils_hash', nodecl> end
function tico.replace_char(str: cstring, find: cuchar, replace: cuchar): cstring <cimport'tico_replace_char', nodecl> end
function tico.utf8_codepoint(p: *cuchar, codepoint: *cint): *cuchar <cimport'tico_utf8_codepoint', nodecl> end
function tico.utf8_encode(c: *cuchar, codepoint: cint) <cimport'tico_utf8_encode', nodecl> end
function tico.utf8_decode(p: *cuchar): cint <cimport'tico_utf8_decode', nodecl> end
function tico.write_buffer_header(name: cstring, text: cstring, size: clong) <cimport'tico_write_buffer_header', nodecl> end
function tico.set_clipboard(text: cstring) <cimport'tico_set_clipboard', nodecl> end
function tico.get_clipboard(): cstring <cimport'tico_get_clipboard', nodecl> end
local tc_Rect: type <cimport, nodecl> = @record{
  x: cint,
  y: cint,
  w: cint,
  h: cint
}
local tc_Rectf: type <cimport, nodecl> = @record{
  x: float32,
  y: float32,
  w: float32,
  h: float32
}
local tc_Circle: type <cimport, nodecl> = @record{
  x: cint,
  y: cint,
  radius: cint
}
local tc_Circlef: type <cimport, nodecl> = @record{
  x: float32,
  y: float32,
  radius: float32
}
local tc_Color: type <cimport, nodecl> = @record{
  r: cuchar,
  g: cuchar,
  b: cuchar,
  a: cuchar
}
local TIC_SHADER_UNIFORM_: type <cimport, nodecl, using> = @enum(cint){
  UNIFORM_INT = 0,
  UNIFORM_VEC2I = 1,
  UNIFORM_VEC3I = 2,
  UNIFORM_VEC4I = 3,
  UNIFORM_FLOAT = 4,
  UNIFORM_VEC2 = 5,
  UNIFORM_VEC3 = 6,
  UNIFORM_VEC4 = 7,
  UNIFORM_MATRIX = 8
}
local tc_Texture: type <cimport, nodecl> = @record{
  id: cuint,
  width: cint,
  height: cint,
  wrap: [2]cint,
  filter: [2]cint
}
local tc_Image: type <cimport, nodecl> = @record{
  texture: tc_Texture,
  width: cint,
  height: cint
}
local tc_Canvas: type <cimport, nodecl> = @record{
  id: cuint,
  tex: tc_Texture,
  width: cint,
  height: cint
}
local tc_Shader: type <cimport, nodecl> = @record{
  program: cuint
}
local tc_CharacterInfo: type <cimport, nodecl> = @record{
  ax: cint,
  ay: cint,
  bw: cint,
  bh: cint,
  bl: cint,
  bt: cint,
  tx: float32
}
local tc_Font: type <cimport, nodecl> = @record{
  texture: tc_Texture,
  c: [256]tc_CharacterInfo,
  size: cuchar,
  info: stbtt_fontinfo,
  ptsize: float32,
  scale: float32,
  baseline: cint,
  data: pointer,
  atlasVao: cuint,
  atlasVbo: cuint
}
local tc_Vec2: type <cimport, nodecl> = @record{
  x: float32,
  y: float32
}
local tc_Vec3: type <cimport, nodecl> = @record{
  x: float32,
  y: float32,
  z: float32
}
local tc_Vec4: type <cimport, nodecl> = @record{
  x: float32,
  y: float32,
  z: float32,
  w: float32
}
local tc_Matrix: type <cimport, nodecl> = @record{
  m00: float32,
  m10: float32,
  m20: float32,
  m30: float32,
  m01: float32,
  m11: float32,
  m21: float32,
  m31: float32,
  m02: float32,
  m12: float32,
  m22: float32,
  m32: float32,
  m03: float32,
  m13: float32,
  m23: float32,
  m33: float32
}
function tico.vec2_add(v: *tc_Vec2, a: tc_Vec2, b: tc_Vec2) <cimport'tico_vec2_add', nodecl> end
function tico.vec2_sub(v: *tc_Vec2, a: tc_Vec2, b: tc_Vec2) <cimport'tico_vec2_sub', nodecl> end
function tico.vec2_mul(v: *tc_Vec2, a: tc_Vec2, number: float32) <cimport'tico_vec2_mul', nodecl> end
function tico.vec2_div(v: *tc_Vec2, a: tc_Vec2, number: float32) <cimport'tico_vec2_div', nodecl> end
function tico.vec2_dot(a: tc_Vec2, b: tc_Vec2): float32 <cimport'tico_vec2_dot', nodecl> end
function tico.vec2_print(v: tc_Vec2) <cimport'tico_vec2_print', nodecl> end
function tico.vec2_equals(a: tc_Vec2, b: tc_Vec2): boolean <cimport'tico_vec2_equals', nodecl> end
function tico.vec2_len(v: tc_Vec2): float32 <cimport'tico_vec2_len', nodecl> end
function tico.vec2_normalize(v: *tc_Vec2, u: tc_Vec2) <cimport'tico_vec2_normalize', nodecl> end
function tico.vec2_distance(a: tc_Vec2, b: tc_Vec2): float32 <cimport'tico_vec2_distance', nodecl> end
function tico.vec2_min(r: *tc_Vec2, a: tc_Vec2, b: tc_Vec2) <cimport'tico_vec2_min', nodecl> end
function tico.vec2_max(r: *tc_Vec2, a: tc_Vec2, b: tc_Vec2) <cimport'tico_vec2_max', nodecl> end
function tico.vec2_lerp(r: *tc_Vec2, a: tc_Vec2, b: tc_Vec2, t: float32) <cimport'tico_vec2_lerp', nodecl> end
function tico.vec2_perpdot(v: tc_Vec2, w: tc_Vec2): float32 <cimport'tico_vec2_perpdot', nodecl> end
function tico.vec2_normal(r: *tc_Vec2, v: tc_Vec2) <cimport'tico_vec2_normal', nodecl> end
function tico.vec2_projection(r: *tc_Vec2, v: tc_Vec2, w: tc_Vec2) <cimport'tico_vec2_projection', nodecl> end
function tico.vec2_angle(v: tc_Vec2): float32 <cimport'tico_vec2_angle', nodecl> end
function tico.vec3_add(v: *tc_Vec3, a: tc_Vec3, b: tc_Vec3) <cimport'tico_vec3_add', nodecl> end
function tico.vec3_sub(v: *tc_Vec3, a: tc_Vec3, b: tc_Vec3) <cimport'tico_vec3_sub', nodecl> end
function tico.vec3_mul(v: *tc_Vec3, a: tc_Vec3, number: float32) <cimport'tico_vec3_mul', nodecl> end
function tico.vec3_div(v: *tc_Vec3, a: tc_Vec3, number: float32) <cimport'tico_vec3_div', nodecl> end
function tico.vec3_dot(a: tc_Vec3, b: tc_Vec3): float32 <cimport'tico_vec3_dot', nodecl> end
function tico.vec3_print(v: tc_Vec3) <cimport'tico_vec3_print', nodecl> end
function tico.vec3_equals(a: tc_Vec3, b: tc_Vec3): boolean <cimport'tico_vec3_equals', nodecl> end
function tico.vec3_len(v: tc_Vec3): float32 <cimport'tico_vec3_len', nodecl> end
function tico.vec3_normalize(v: *tc_Vec3, u: tc_Vec3) <cimport'tico_vec3_normalize', nodecl> end
function tico.vec3_distance(a: tc_Vec3, b: tc_Vec3): float32 <cimport'tico_vec3_distance', nodecl> end
function tico.vec3_min(r: *tc_Vec3, a: tc_Vec3, b: tc_Vec3) <cimport'tico_vec3_min', nodecl> end
function tico.vec3_max(r: *tc_Vec3, a: tc_Vec3, b: tc_Vec3) <cimport'tico_vec3_max', nodecl> end
function tico.vec3_lerp(r: *tc_Vec3, a: tc_Vec3, b: tc_Vec3, t: float32) <cimport'tico_vec3_lerp', nodecl> end
function tico.vec3_cross(r: *tc_Vec3, a: tc_Vec3, b: tc_Vec3) <cimport'tico_vec3_cross', nodecl> end
function tico.vec3_reflect(r: *tc_Vec3, v: tc_Vec3, n: tc_Vec3) <cimport'tico_vec3_reflect', nodecl> end
function tico.vec4_add(v: *tc_Vec4, a: tc_Vec4, b: tc_Vec4) <cimport'tico_vec4_add', nodecl> end
function tico.vec4_sub(v: *tc_Vec4, a: tc_Vec4, b: tc_Vec4) <cimport'tico_vec4_sub', nodecl> end
function tico.vec4_mul(v: *tc_Vec4, a: tc_Vec4, number: float32) <cimport'tico_vec4_mul', nodecl> end
function tico.vec4_div(v: *tc_Vec4, a: tc_Vec4, number: float32) <cimport'tico_vec4_div', nodecl> end
function tico.vec4_dot(a: tc_Vec4, b: tc_Vec4): float32 <cimport'tico_vec4_dot', nodecl> end
function tico.vec4_print(v: tc_Vec4) <cimport'tico_vec4_print', nodecl> end
function tico.vec4_equals(a: tc_Vec4, b: tc_Vec4): boolean <cimport'tico_vec4_equals', nodecl> end
function tico.vec4_len(v: tc_Vec4): float32 <cimport'tico_vec4_len', nodecl> end
function tico.vec4_normalize(v: *tc_Vec4, u: tc_Vec4) <cimport'tico_vec4_normalize', nodecl> end
function tico.vec4_distance(a: tc_Vec4, b: tc_Vec4): float32 <cimport'tico_vec4_distance', nodecl> end
function tico.vec4_min(r: *tc_Vec4, a: tc_Vec4, b: tc_Vec4) <cimport'tico_vec4_min', nodecl> end
function tico.vec4_max(r: *tc_Vec4, a: tc_Vec4, b: tc_Vec4) <cimport'tico_vec4_max', nodecl> end
function tico.vec4_lerp(r: *tc_Vec4, a: tc_Vec4, b: tc_Vec4, t: float32) <cimport'tico_vec4_lerp', nodecl> end
function tico.vec4_cross(r: *tc_Vec4, a: tc_Vec4, b: tc_Vec4) <cimport'tico_vec4_cross', nodecl> end
function tico.vec4_reflect(r: *tc_Vec4, v: tc_Vec4, n: tc_Vec4) <cimport'tico_vec4_reflect', nodecl> end
function tico.matrix_identity(m: *tc_Matrix) <cimport'tico_matrix_identity', nodecl> end
function tico.matrix_clone(m: *tc_Matrix, s: tc_Matrix) <cimport'tico_matrix_clone', nodecl> end
function tico.matrix_equals(a: tc_Matrix, b: tc_Matrix): boolean <cimport'tico_matrix_equals', nodecl> end
function tico.matrix_print(m: tc_Matrix) <cimport'tico_matrix_print', nodecl> end
function tico.matrix_row(v: *tc_Vec4, m: tc_Matrix, row: cint) <cimport'tico_matrix_row', nodecl> end
function tico.matrix_transpose(m: *tc_Matrix, n: tc_Matrix) <cimport'tico_matrix_transpose', nodecl> end
function tico.matrix_translate(r: *tc_Matrix, x: float32, y: float32, z: float32) <cimport'tico_matrix_translate', nodecl> end
function tico.matrix_translate_in_place(r: *tc_Matrix, x: float32, y: float32, z: float32) <cimport'tico_matrix_translate_in_place', nodecl> end
function tico.matrix_translatev(r: *tc_Matrix, v: tc_Vec3) <cimport'tico_matrix_translatev', nodecl> end
function tico.matrix_scale(r: *tc_Matrix, m: tc_Matrix, s: float32) <cimport'tico_matrix_scale', nodecl> end
function tico.matrix_scale_aniso(m: *tc_Matrix, a: tc_Matrix, x: float32, y: float32, z: float32) <cimport'tico_matrix_scale_aniso', nodecl> end
function tico.matrix_scaleV(r: *tc_Matrix, v: tc_Vec3) <cimport'tico_matrix_scaleV', nodecl> end
function tico.matrix_from_vec3_mul_outer(m: *tc_Matrix, a: tc_Vec3, b: tc_Vec3) <cimport'tico_matrix_from_vec3_mul_outer', nodecl> end
function tico.matrix_mul_vec4(v: *tc_Vec4, m: tc_Matrix, n: tc_Vec4) <cimport'tico_matrix_mul_vec4', nodecl> end
function tico.matrix_mul(r: *tc_Matrix, m: tc_Matrix, n: tc_Matrix) <cimport'tico_matrix_mul', nodecl> end
function tico.matrix_rotate(r: *tc_Matrix, m: tc_Matrix, x: float32, y: float32, z: float32, angle: float32) <cimport'tico_matrix_rotate', nodecl> end
function tico.matrix_rotate_x(r: *tc_Matrix, m: tc_Matrix, angle: float32) <cimport'tico_matrix_rotate_x', nodecl> end
function tico.matrix_rotate_y(r: *tc_Matrix, m: tc_Matrix, angle: float32) <cimport'tico_matrix_rotate_y', nodecl> end
function tico.matrix_rotate_z(r: *tc_Matrix, m: tc_Matrix, angle: float32) <cimport'tico_matrix_rotate_z', nodecl> end
function tico.matrix_rotate2D(r: *tc_Matrix, m: tc_Matrix, angle: float32) <cimport'tico_matrix_rotate2D', nodecl> end
function tico.matrix_invert(r: *tc_Matrix, m: tc_Matrix) <cimport'tico_matrix_invert', nodecl> end
function tico.matrix_orthonormalize(r: *tc_Matrix, m: tc_Matrix) <cimport'tico_matrix_orthonormalize', nodecl> end
function tico.matrix_frustum(m: *tc_Matrix, l: float32, r: float32, b: float32, t: float32, n: float32, f: float32) <cimport'tico_matrix_frustum', nodecl> end
function tico.matrix_ortho(m: *tc_Matrix, l: float32, r: float32, b: float32, t: float32, n: float32, f: float32) <cimport'tico_matrix_ortho', nodecl> end
function tico.matrix_perspective(m: *tc_Matrix, y_fov: float32, aspect: float32, n: float32, f: float32) <cimport'tico_matrix_perspective', nodecl> end
function tico.matrix_look_at(m: *tc_Matrix, eye: tc_Vec3, center: tc_Vec3, up: tc_Vec3) <cimport'tico_matrix_look_at', nodecl> end
function tico.lerp(a: float32, b: float32, t: float32): float32 <cimport'tico_lerp', nodecl> end
function tico.round(n: float32): float32 <cimport'tico_round', nodecl> end
function tico.distance(a: float32, b: float32): float32 <cimport'tico_distance', nodecl> end
function tico.sign(a: float32): cint <cimport'tico_sign', nodecl> end
function tico.angle(x0: float32, y0: float32, x1: float32, y1: float32): float32 <cimport'tico_angle', nodecl> end
local TIC_FILE_TYPE_: type <cimport, nodecl, using> = @enum(cint){
  FILE = 0,
  DIRECTORY = 1,
  SYMLINK = 2
}
local TIC_WRITE_MODE_: type <cimport, nodecl, using> = @enum(cint){
  WRITE = 0,
  APPEND = 1,
  BINARY = 2
}
local tc_Filesystem: type <cimport, nodecl, forwarddecl> = @record{}
tc_Filesystem = @record{
  projectPath: [256]cchar,
  exePath: [256]cchar,
  readFile: function(*tc_Filesystem, cstring, *csize): *cuchar --[[ReadFunction]],
  writeFile: function(*tc_Filesystem, cstring, cstring, csize, TIC_WRITE_MODE_): void --[[WriteFunction]],
  fileExists: function(*tc_Filesystem, cstring): boolean --[[FileExistsFunction]],
  packed: cint
}
function tico.filesystem_init(fs: *tc_Filesystem): cint <cimport'tico_filesystem_init', nodecl> end
function tico.json_is_valid(filename: cstring): boolean <cimport'tico_json_is_valid', nodecl> end
function tico.json_open(filename: cstring): *cJSON <cimport'tico_json_open', nodecl> end
function tico.json_parse(jsonStr: cstring): *cJSON <cimport'tico_json_parse', nodecl> end
function tico.json_clone(src: *cJSON): *cJSON <cimport'tico_json_clone', nodecl> end
function tico.json_save(filename: cstring, json: *cJSON) <cimport'tico_json_save', nodecl> end
function tico.json_print(json: *cJSON): cstring <cimport'tico_json_print', nodecl> end
function tico.json_create(): *cJSON <cimport'tico_json_create', nodecl> end
function tico.json_delete(json: *cJSON) <cimport'tico_json_delete', nodecl> end
function tico.json_add_item(json: *cJSON, name: cstring, item: *cJSON): cint <cimport'tico_json_add_item', nodecl> end
function tico.json_get_item(json: *cJSON, name: cstring, index: cint): *cJSON <cimport'tico_json_get_item', nodecl> end
function tico.json_create_string(value: cstring): *cJSON <cimport'tico_json_create_string', nodecl> end
function tico.json_is_string(json: *cJSON): boolean <cimport'tico_json_is_string', nodecl> end
function tico.json_set_string(json: *cJSON, value: cstring) <cimport'tico_json_set_string', nodecl> end
function tico.json_to_string(json: *cJSON): cstring <cimport'tico_json_to_string', nodecl> end
function tico.json_opt_string(json: *cJSON, opt: cstring): cstring <cimport'tico_json_opt_string', nodecl> end
function tico.json_add_string(json: *cJSON, name: cstring, value: cstring): *cJSON <cimport'tico_json_add_string', nodecl> end
function tico.json_get_string(json: *cJSON, name: cstring, index: cint): cstring <cimport'tico_json_get_string', nodecl> end
function tico.json_get_opt_string(json: *cJSON, name: cstring, index: cint, opt: cstring): cstring <cimport'tico_json_get_opt_string', nodecl> end
function tico.json_create_number(value: float32): *cJSON <cimport'tico_json_create_number', nodecl> end
function tico.json_is_number(json: *cJSON): boolean <cimport'tico_json_is_number', nodecl> end
function tico.json_set_number(json: *cJSON, value: float32) <cimport'tico_json_set_number', nodecl> end
function tico.json_to_number(json: *cJSON): float32 <cimport'tico_json_to_number', nodecl> end
function tico.json_opt_number(json: *cJSON, opt: float32): float32 <cimport'tico_json_opt_number', nodecl> end
function tico.json_add_number(json: *cJSON, name: cstring, value: float32): *cJSON <cimport'tico_json_add_number', nodecl> end
function tico.json_get_number(json: *cJSON, name: cstring, index: cint): float32 <cimport'tico_json_get_number', nodecl> end
function tico.json_get_opt_number(json: *cJSON, name: cstring, index: cint, opt: float32): float32 <cimport'tico_json_get_opt_number', nodecl> end
function tico.json_create_boolean(value: cint): *cJSON <cimport'tico_json_create_boolean', nodecl> end
function tico.json_is_boolean(json: *cJSON): boolean <cimport'tico_json_is_boolean', nodecl> end
function tico.json_set_boolean(json: *cJSON, value: cint) <cimport'tico_json_set_boolean', nodecl> end
function tico.json_to_boolean(json: *cJSON): cint <cimport'tico_json_to_boolean', nodecl> end
function tico.json_opt_boolean(json: *cJSON, opt: cint): cint <cimport'tico_json_opt_boolean', nodecl> end
function tico.json_add_boolean(json: *cJSON, name: cstring, value: cint): *cJSON <cimport'tico_json_add_boolean', nodecl> end
function tico.json_get_boolean(json: *cJSON, name: cstring, index: cint): cint <cimport'tico_json_get_boolean', nodecl> end
function tico.json_get_opt_boolean(json: *cJSON, name: cstring, index: cint, opt: cint): cint <cimport'tico_json_get_opt_boolean', nodecl> end
function tico.json_create_vec2(value: tc_Vec2): *cJSON <cimport'tico_json_create_vec2', nodecl> end
function tico.json_is_vec2(json: *cJSON): boolean <cimport'tico_json_is_vec2', nodecl> end
function tico.json_set_vec2(json: *cJSON, value: tc_Vec2) <cimport'tico_json_set_vec2', nodecl> end
function tico.json_to_vec2(json: *cJSON): tc_Vec2 <cimport'tico_json_to_vec2', nodecl> end
function tico.json_opt_vec2(json: *cJSON, opt: tc_Vec2): tc_Vec2 <cimport'tico_json_opt_vec2', nodecl> end
function tico.json_add_vec2(json: *cJSON, name: cstring, value: tc_Vec2): *cJSON <cimport'tico_json_add_vec2', nodecl> end
function tico.json_get_vec2(json: *cJSON, name: cstring, index: cint): tc_Vec2 <cimport'tico_json_get_vec2', nodecl> end
function tico.json_get_opt_vec2(json: *cJSON, name: cstring, index: cint, opt: tc_Vec2): tc_Vec2 <cimport'tico_json_get_opt_vec2', nodecl> end
function tico.json_create_vec3(value: tc_Vec3): *cJSON <cimport'tico_json_create_vec3', nodecl> end
function tico.json_is_vec3(json: *cJSON): boolean <cimport'tico_json_is_vec3', nodecl> end
function tico.json_set_vec3(json: *cJSON, value: tc_Vec3) <cimport'tico_json_set_vec3', nodecl> end
function tico.json_to_vec3(json: *cJSON): tc_Vec3 <cimport'tico_json_to_vec3', nodecl> end
function tico.json_opt_vec3(json: *cJSON, opt: tc_Vec3): tc_Vec3 <cimport'tico_json_opt_vec3', nodecl> end
function tico.json_add_vec3(json: *cJSON, name: cstring, value: tc_Vec3): *cJSON <cimport'tico_json_add_vec3', nodecl> end
function tico.json_get_vec3(json: *cJSON, name: cstring, index: cint): tc_Vec3 <cimport'tico_json_get_vec3', nodecl> end
function tico.json_get_opt_vec3(json: *cJSON, name: cstring, index: cint, opt: tc_Vec3): tc_Vec3 <cimport'tico_json_get_opt_vec3', nodecl> end
function tico.json_create_vec4(value: tc_Vec4): *cJSON <cimport'tico_json_create_vec4', nodecl> end
function tico.json_is_vec4(json: *cJSON): boolean <cimport'tico_json_is_vec4', nodecl> end
function tico.json_set_vec4(json: *cJSON, value: tc_Vec4) <cimport'tico_json_set_vec4', nodecl> end
function tico.json_to_vec4(json: *cJSON): tc_Vec4 <cimport'tico_json_to_vec4', nodecl> end
function tico.json_opt_vec4(json: *cJSON, opt: tc_Vec4): tc_Vec4 <cimport'tico_json_opt_vec4', nodecl> end
function tico.json_add_vec4(json: *cJSON, name: cstring, value: tc_Vec4): *cJSON <cimport'tico_json_add_vec4', nodecl> end
function tico.json_get_vec4(json: *cJSON, name: cstring, index: cint): tc_Vec4 <cimport'tico_json_get_vec4', nodecl> end
function tico.json_get_opt_vec4(json: *cJSON, name: cstring, index: cint, opt: tc_Vec4): tc_Vec4 <cimport'tico_json_get_opt_vec4', nodecl> end
function tico.json_create_array(value: *cJSON): *cJSON <cimport'tico_json_create_array', nodecl> end
function tico.json_is_array(json: *cJSON): boolean <cimport'tico_json_is_array', nodecl> end
function tico.json_set_array(json: *cJSON, value: *cJSON) <cimport'tico_json_set_array', nodecl> end
function tico.json_to_array(json: *cJSON): *cJSON <cimport'tico_json_to_array', nodecl> end
function tico.json_opt_array(json: *cJSON, opt: *cJSON): *cJSON <cimport'tico_json_opt_array', nodecl> end
function tico.json_add_array(json: *cJSON, name: cstring, value: *cJSON): *cJSON <cimport'tico_json_add_array', nodecl> end
function tico.json_get_array(json: *cJSON, name: cstring, index: cint): *cJSON <cimport'tico_json_get_array', nodecl> end
function tico.json_get_opt_array(json: *cJSON, name: cstring, index: cint, opt: *cJSON): *cJSON <cimport'tico_json_get_opt_array', nodecl> end
function tico.json_create_int_array(value: *cint): *cJSON <cimport'tico_json_create_int_array', nodecl> end
function tico.json_is_int_array(json: *cJSON): boolean <cimport'tico_json_is_int_array', nodecl> end
function tico.json_set_int_array(json: *cJSON, value: *cint) <cimport'tico_json_set_int_array', nodecl> end
function tico.json_to_int_array(json: *cJSON): *cint <cimport'tico_json_to_int_array', nodecl> end
function tico.json_opt_int_array(json: *cJSON, opt: *cint): *cint <cimport'tico_json_opt_int_array', nodecl> end
function tico.json_add_int_array(json: *cJSON, name: cstring, value: *cint): *cJSON <cimport'tico_json_add_int_array', nodecl> end
function tico.json_get_int_array(json: *cJSON, name: cstring, index: cint): *cint <cimport'tico_json_get_int_array', nodecl> end
function tico.json_get_opt_int_array(json: *cJSON, name: cstring, index: cint, opt: *cint): *cint <cimport'tico_json_get_opt_int_array', nodecl> end
function tico.json_create_object(value: *cJSON): *cJSON <cimport'tico_json_create_object', nodecl> end
function tico.json_is_object(json: *cJSON): boolean <cimport'tico_json_is_object', nodecl> end
function tico.json_set_object(json: *cJSON, value: *cJSON) <cimport'tico_json_set_object', nodecl> end
function tico.json_to_object(json: *cJSON): *cJSON <cimport'tico_json_to_object', nodecl> end
function tico.json_opt_object(json: *cJSON, opt: *cJSON): *cJSON <cimport'tico_json_opt_object', nodecl> end
function tico.json_add_object(json: *cJSON, name: cstring, value: *cJSON): *cJSON <cimport'tico_json_add_object', nodecl> end
function tico.json_get_object(json: *cJSON, name: cstring, index: cint): *cJSON <cimport'tico_json_get_object', nodecl> end
function tico.json_get_opt_object(json: *cJSON, name: cstring, index: cint, opt: *cJSON): *cJSON <cimport'tico_json_get_opt_object', nodecl> end
function tico.json_to_circle(json: *cJSON): tc_Circlef <cimport'tico_json_to_circle', nodecl> end
function tico.json_get_array_size(json: *cJSON): cint <cimport'tico_json_get_array_size', nodecl> end
local tc_Field: type <cimport, nodecl, forwarddecl> = @record{}
local tc_Meta: type <cimport, nodecl, forwarddecl> = @record{}
local TIC_FIELD_TYPE_: type <cimport, nodecl, using> = @enum(cint){
  FIELD_TYPE_NULL = 0,
  FIELD_TYPE_NUMBER = 1,
  FIELD_TYPE_STRING = 2,
  FIELD_TYPE_BOOLEAN = 3,
  FIELD_TYPE_VEC2 = 4,
  FIELD_TYPE_VEC3 = 5,
  FIELD_TYPE_VEC4 = 6,
  FIELD_TYPE_ARRAY = 7,
  FIELD_TYPE_OBJECT = 8,
  FIELD_TYPE_CUSTOM = 9,
  FIELD_TYPE_REFERENCE = 10,
  FIELD_TYPE_MAX = 11
}
local tc_MetaFn: type <cimport, nodecl, ctypedef> = @record{
  draw: function(*tc_Field, tc_Vec2, float32): void --[[drawField]],
  imgui: function(): void --[[imguiField]]
}
local tc_FieldFn: type = @tc_MetaFn
local tc_FieldType: type <cimport, nodecl> = @record{
  load: function(*cJSON): *tc_Field --[[loadFromJson]],
  json: function(*cJSON): *tc_Field --[[exportToJson]],
  draw: function(*tc_Field, tc_Vec2, float32): void --[[drawField]],
  imgui: function(): void --[[imguiField]]
}
local tc_Serialization: type <cimport, nodecl> = @record{
  types: map_fieldtype_t
}
tc_Field = @record{
  type: TIC_FIELD_TYPE_,
  field_type: *tc_FieldType,
  name: [128]cchar,
  meta: *tc_Field,
  own_meta: cint,
  number: float32,
  string: [256]cchar,
  boolean: cint,
  vec2: tc_Vec2,
  vec3: tc_Vec3,
  vec4: tc_Vec4,
  ref: *tc_Field,
  user_data: pointer,
  prev: *tc_Field,
  next: *tc_Field,
  parent: *tc_Field,
  child: *tc_Field
}
tc_Meta = @record{
  fields: map_field_t
}
function tico.serialization_init() <cimport'tico_serialization_init', nodecl> end
function tico.meta_from_json(json: *cJSON): *tc_Meta <cimport'tico_meta_from_json', nodecl> end
function tico.meta_to_field(meta: *tc_Meta): *tc_Field <cimport'tico_meta_to_field', nodecl> end
function tico.meta_destroy(meta: *tc_Meta) <cimport'tico_meta_destroy', nodecl> end
function tico.meta_field_draw(meta: *tc_Meta, field: *tc_Field) <cimport'tico_meta_field_draw', nodecl> end
function tico.meta_field_imgui(meta: *tc_Meta, field: *tc_Field) <cimport'tico_meta_field_imgui', nodecl> end
function tico.field_create(type: TIC_FIELD_TYPE_): *tc_Field <cimport'tico_field_create', nodecl> end
function tico.field_load(path: cstring): *tc_Field <cimport'tico_field_load', nodecl> end
function tico.field_from_json(json: *cJSON, meta_field: *tc_Field): *tc_Field <cimport'tico_field_from_json', nodecl> end
function tico.field_delete(field: *tc_Field) <cimport'tico_field_delete', nodecl> end
function tico.field_push(field: *tc_Field, index: cint, item: *tc_Field) <cimport'tico_field_push', nodecl> end
function tico.field_set(field: *tc_Field, name: cstring, item: *tc_Field): *tc_Field <cimport'tico_field_set', nodecl> end
function tico.field_get(field: *tc_Field, name: cstring): *tc_Field <cimport'tico_field_get', nodecl> end
function tico.field_length(field: *tc_Field): cint <cimport'tico_field_length', nodecl> end
function tico.field_draw_imgui(field: *tc_Field) <cimport'tico_field_draw_imgui', nodecl> end
function tico.field_draw(field: *tc_Field, pos: tc_Vec2, scale: float32) <cimport'tico_field_draw', nodecl> end
function tico.field_vec2_array_from_json(json: *cJSON): *tc_Field <cimport'tico_field_vec2_array_from_json', nodecl> end
function tico.field_create_number(value: float32): *tc_Field <cimport'tico_field_create_number', nodecl> end
function tico.field_number_from_json(json: *cJSON): *tc_Field <cimport'tico_field_number_from_json', nodecl> end
function tico.field_get_number(field: *tc_Field, name: cstring): float32 <cimport'tico_field_get_number', nodecl> end
function tico.field_get_opt_number(field: *tc_Field, name: cstring, opt: float32): float32 <cimport'tico_field_get_opt_number', nodecl> end
function tico.field_add_number(field: *tc_Field, name: cstring, value: float32): *tc_Field <cimport'tico_field_add_number', nodecl> end
function tico.field_to_number(field: *tc_Field): float32 <cimport'tico_field_to_number', nodecl> end
function tico.field_to_opt_number(field: *tc_Field, value: float32): float32 <cimport'tico_field_to_opt_number', nodecl> end
function tico.field_set_number(field: *tc_Field, value: float32) <cimport'tico_field_set_number', nodecl> end
function tico.field_number_imgui(field: *tc_Field) <cimport'tico_field_number_imgui', nodecl> end
function tico.field_draw_number(field: *tc_Field, pos: tc_Vec2, scale: float32) <cimport'tico_field_draw_number', nodecl> end
function tico.field_number_to_json(field: *tc_Field, export_meta: cint): *cJSON <cimport'tico_field_number_to_json', nodecl> end
function tico.meta_draw_number(a1: *tc_Field, a2: *tc_Field) <cimport'tico_meta_draw_number', nodecl> end
function tico.meta_imgui_number(a1: *tc_Field, a2: *tc_Field) <cimport'tico_meta_imgui_number', nodecl> end
function tico.field_create_string(value: cstring): *tc_Field <cimport'tico_field_create_string', nodecl> end
function tico.field_string_from_json(json: *cJSON): *tc_Field <cimport'tico_field_string_from_json', nodecl> end
function tico.field_get_string(field: *tc_Field, name: cstring): cstring <cimport'tico_field_get_string', nodecl> end
function tico.field_get_opt_string(field: *tc_Field, name: cstring, opt: cstring): cstring <cimport'tico_field_get_opt_string', nodecl> end
function tico.field_add_string(field: *tc_Field, name: cstring, value: cstring): *tc_Field <cimport'tico_field_add_string', nodecl> end
function tico.field_to_string(field: *tc_Field): cstring <cimport'tico_field_to_string', nodecl> end
function tico.field_to_opt_string(field: *tc_Field, value: cstring): cstring <cimport'tico_field_to_opt_string', nodecl> end
function tico.field_set_string(field: *tc_Field, value: cstring) <cimport'tico_field_set_string', nodecl> end
function tico.field_string_imgui(field: *tc_Field) <cimport'tico_field_string_imgui', nodecl> end
function tico.field_draw_string(field: *tc_Field, pos: tc_Vec2, scale: float32) <cimport'tico_field_draw_string', nodecl> end
function tico.field_string_to_json(field: *tc_Field, export_meta: cint): *cJSON <cimport'tico_field_string_to_json', nodecl> end
function tico.meta_draw_string(a1: *tc_Field, a2: *tc_Field) <cimport'tico_meta_draw_string', nodecl> end
function tico.meta_imgui_string(a1: *tc_Field, a2: *tc_Field) <cimport'tico_meta_imgui_string', nodecl> end
function tico.field_create_boolean(value: cint): *tc_Field <cimport'tico_field_create_boolean', nodecl> end
function tico.field_boolean_from_json(json: *cJSON): *tc_Field <cimport'tico_field_boolean_from_json', nodecl> end
function tico.field_get_boolean(field: *tc_Field, name: cstring): cint <cimport'tico_field_get_boolean', nodecl> end
function tico.field_get_opt_boolean(field: *tc_Field, name: cstring, opt: cint): cint <cimport'tico_field_get_opt_boolean', nodecl> end
function tico.field_add_boolean(field: *tc_Field, name: cstring, value: cint): *tc_Field <cimport'tico_field_add_boolean', nodecl> end
function tico.field_to_boolean(field: *tc_Field): cint <cimport'tico_field_to_boolean', nodecl> end
function tico.field_to_opt_boolean(field: *tc_Field, value: cint): cint <cimport'tico_field_to_opt_boolean', nodecl> end
function tico.field_set_boolean(field: *tc_Field, value: cint) <cimport'tico_field_set_boolean', nodecl> end
function tico.field_boolean_imgui(field: *tc_Field) <cimport'tico_field_boolean_imgui', nodecl> end
function tico.field_draw_boolean(field: *tc_Field, pos: tc_Vec2, scale: float32) <cimport'tico_field_draw_boolean', nodecl> end
function tico.field_boolean_to_json(field: *tc_Field, export_meta: cint): *cJSON <cimport'tico_field_boolean_to_json', nodecl> end
function tico.meta_draw_boolean(a1: *tc_Field, a2: *tc_Field) <cimport'tico_meta_draw_boolean', nodecl> end
function tico.meta_imgui_boolean(a1: *tc_Field, a2: *tc_Field) <cimport'tico_meta_imgui_boolean', nodecl> end
function tico.field_create_vec2(value: tc_Vec2): *tc_Field <cimport'tico_field_create_vec2', nodecl> end
function tico.field_vec2_from_json(json: *cJSON): *tc_Field <cimport'tico_field_vec2_from_json', nodecl> end
function tico.field_get_vec2(field: *tc_Field, name: cstring): tc_Vec2 <cimport'tico_field_get_vec2', nodecl> end
function tico.field_get_opt_vec2(field: *tc_Field, name: cstring, opt: tc_Vec2): tc_Vec2 <cimport'tico_field_get_opt_vec2', nodecl> end
function tico.field_add_vec2(field: *tc_Field, name: cstring, value: tc_Vec2): *tc_Field <cimport'tico_field_add_vec2', nodecl> end
function tico.field_to_vec2(field: *tc_Field): tc_Vec2 <cimport'tico_field_to_vec2', nodecl> end
function tico.field_to_opt_vec2(field: *tc_Field, value: tc_Vec2): tc_Vec2 <cimport'tico_field_to_opt_vec2', nodecl> end
function tico.field_set_vec2(field: *tc_Field, value: tc_Vec2) <cimport'tico_field_set_vec2', nodecl> end
function tico.field_vec2_imgui(field: *tc_Field) <cimport'tico_field_vec2_imgui', nodecl> end
function tico.field_draw_vec2(field: *tc_Field, pos: tc_Vec2, scale: float32) <cimport'tico_field_draw_vec2', nodecl> end
function tico.field_vec2_to_json(field: *tc_Field, export_meta: cint): *cJSON <cimport'tico_field_vec2_to_json', nodecl> end
function tico.meta_draw_vec2(a1: *tc_Field, a2: *tc_Field) <cimport'tico_meta_draw_vec2', nodecl> end
function tico.meta_imgui_vec2(a1: *tc_Field, a2: *tc_Field) <cimport'tico_meta_imgui_vec2', nodecl> end
function tico.field_create_vec3(value: tc_Vec3): *tc_Field <cimport'tico_field_create_vec3', nodecl> end
function tico.field_vec3_from_json(json: *cJSON): *tc_Field <cimport'tico_field_vec3_from_json', nodecl> end
function tico.field_get_vec3(field: *tc_Field, name: cstring): tc_Vec3 <cimport'tico_field_get_vec3', nodecl> end
function tico.field_get_opt_vec3(field: *tc_Field, name: cstring, opt: tc_Vec3): tc_Vec3 <cimport'tico_field_get_opt_vec3', nodecl> end
function tico.field_add_vec3(field: *tc_Field, name: cstring, value: tc_Vec3): *tc_Field <cimport'tico_field_add_vec3', nodecl> end
function tico.field_to_vec3(field: *tc_Field): tc_Vec3 <cimport'tico_field_to_vec3', nodecl> end
function tico.field_to_opt_vec3(field: *tc_Field, value: tc_Vec3): tc_Vec3 <cimport'tico_field_to_opt_vec3', nodecl> end
function tico.field_set_vec3(field: *tc_Field, value: tc_Vec3) <cimport'tico_field_set_vec3', nodecl> end
function tico.field_vec3_imgui(field: *tc_Field) <cimport'tico_field_vec3_imgui', nodecl> end
function tico.field_draw_vec3(field: *tc_Field, pos: tc_Vec2, scale: float32) <cimport'tico_field_draw_vec3', nodecl> end
function tico.field_vec3_to_json(field: *tc_Field, export_meta: cint): *cJSON <cimport'tico_field_vec3_to_json', nodecl> end
function tico.meta_draw_vec3(a1: *tc_Field, a2: *tc_Field) <cimport'tico_meta_draw_vec3', nodecl> end
function tico.meta_imgui_vec3(a1: *tc_Field, a2: *tc_Field) <cimport'tico_meta_imgui_vec3', nodecl> end
function tico.field_create_vec4(value: tc_Vec4): *tc_Field <cimport'tico_field_create_vec4', nodecl> end
function tico.field_vec4_from_json(json: *cJSON): *tc_Field <cimport'tico_field_vec4_from_json', nodecl> end
function tico.field_get_vec4(field: *tc_Field, name: cstring): tc_Vec4 <cimport'tico_field_get_vec4', nodecl> end
function tico.field_get_opt_vec4(field: *tc_Field, name: cstring, opt: tc_Vec4): tc_Vec4 <cimport'tico_field_get_opt_vec4', nodecl> end
function tico.field_add_vec4(field: *tc_Field, name: cstring, value: tc_Vec4): *tc_Field <cimport'tico_field_add_vec4', nodecl> end
function tico.field_to_vec4(field: *tc_Field): tc_Vec4 <cimport'tico_field_to_vec4', nodecl> end
function tico.field_to_opt_vec4(field: *tc_Field, value: tc_Vec4): tc_Vec4 <cimport'tico_field_to_opt_vec4', nodecl> end
function tico.field_set_vec4(field: *tc_Field, value: tc_Vec4) <cimport'tico_field_set_vec4', nodecl> end
function tico.field_vec4_imgui(field: *tc_Field) <cimport'tico_field_vec4_imgui', nodecl> end
function tico.field_draw_vec4(field: *tc_Field, pos: tc_Vec2, scale: float32) <cimport'tico_field_draw_vec4', nodecl> end
function tico.field_vec4_to_json(field: *tc_Field, export_meta: cint): *cJSON <cimport'tico_field_vec4_to_json', nodecl> end
function tico.meta_draw_vec4(a1: *tc_Field, a2: *tc_Field) <cimport'tico_meta_draw_vec4', nodecl> end
function tico.meta_imgui_vec4(a1: *tc_Field, a2: *tc_Field) <cimport'tico_meta_imgui_vec4', nodecl> end
function tico.field_create_array(value: *tc_Field): *tc_Field <cimport'tico_field_create_array', nodecl> end
function tico.field_array_from_json(json: *cJSON): *tc_Field <cimport'tico_field_array_from_json', nodecl> end
function tico.field_get_array(field: *tc_Field, name: cstring): *tc_Field <cimport'tico_field_get_array', nodecl> end
function tico.field_get_opt_array(field: *tc_Field, name: cstring, opt: *tc_Field): *tc_Field <cimport'tico_field_get_opt_array', nodecl> end
function tico.field_add_array(field: *tc_Field, name: cstring, value: *tc_Field): *tc_Field <cimport'tico_field_add_array', nodecl> end
function tico.field_to_array(field: *tc_Field): *tc_Field <cimport'tico_field_to_array', nodecl> end
function tico.field_to_opt_array(field: *tc_Field, value: *tc_Field): *tc_Field <cimport'tico_field_to_opt_array', nodecl> end
function tico.field_set_array(field: *tc_Field, value: *tc_Field) <cimport'tico_field_set_array', nodecl> end
function tico.field_array_imgui(field: *tc_Field) <cimport'tico_field_array_imgui', nodecl> end
function tico.field_draw_array(field: *tc_Field, pos: tc_Vec2, scale: float32) <cimport'tico_field_draw_array', nodecl> end
function tico.field_array_to_json(field: *tc_Field, export_meta: cint): *cJSON <cimport'tico_field_array_to_json', nodecl> end
function tico.meta_draw_array(a1: *tc_Field, a2: *tc_Field) <cimport'tico_meta_draw_array', nodecl> end
function tico.meta_imgui_array(a1: *tc_Field, a2: *tc_Field) <cimport'tico_meta_imgui_array', nodecl> end
function tico.field_create_object(value: *tc_Field): *tc_Field <cimport'tico_field_create_object', nodecl> end
function tico.field_object_from_json(json: *cJSON): *tc_Field <cimport'tico_field_object_from_json', nodecl> end
function tico.field_get_object(field: *tc_Field, name: cstring): *tc_Field <cimport'tico_field_get_object', nodecl> end
function tico.field_get_opt_object(field: *tc_Field, name: cstring, opt: *tc_Field): *tc_Field <cimport'tico_field_get_opt_object', nodecl> end
function tico.field_add_object(field: *tc_Field, name: cstring, value: *tc_Field): *tc_Field <cimport'tico_field_add_object', nodecl> end
function tico.field_to_object(field: *tc_Field): *tc_Field <cimport'tico_field_to_object', nodecl> end
function tico.field_to_opt_object(field: *tc_Field, value: *tc_Field): *tc_Field <cimport'tico_field_to_opt_object', nodecl> end
function tico.field_set_object(field: *tc_Field, value: *tc_Field) <cimport'tico_field_set_object', nodecl> end
function tico.field_object_imgui(field: *tc_Field) <cimport'tico_field_object_imgui', nodecl> end
function tico.field_draw_object(field: *tc_Field, pos: tc_Vec2, scale: float32) <cimport'tico_field_draw_object', nodecl> end
function tico.field_object_to_json(field: *tc_Field, export_meta: cint): *cJSON <cimport'tico_field_object_to_json', nodecl> end
function tico.meta_draw_object(a1: *tc_Field, a2: *tc_Field) <cimport'tico_meta_draw_object', nodecl> end
function tico.meta_imgui_object(a1: *tc_Field, a2: *tc_Field) <cimport'tico_meta_imgui_object', nodecl> end
local tc_Tileset: type <cimport, nodecl> = @record{
  image: *tc_Image,
  tilesize: tc_Vec2,
  tilecount: cint,
  columns: cint,
  bitmasks: *cint,
  rect: *tc_Rectf
}
local tc_Tilemap: type <cimport, nodecl> = @record{
  tileset: *tc_Tileset,
  grid: tc_Vec2,
  width: cint,
  height: cint,
  count: cint,
  data: *cint
}
local tc_Camera: type <cimport, nodecl> = @record{
  area: tc_Rectf,
  size: tc_Vec2,
  offset: tc_Vec2,
  angle: float32
}
local tc_Animation: type <cimport, nodecl> = @record{
  length: cint,
  from: cint,
  to: cint
}
local tc_Sprite: type <cimport, nodecl> = @record{
  animation: [64]cchar,
  frame: cint,
  time: float32,
  speed: float32,
  image: *tc_Image,
  width: cint,
  height: cint,
  count: cint,
  animations: map_anim_t
}
function tico.tileset_create(image: *tc_Image, w: cint, h: cint): tc_Tileset <cimport'tico_tileset_create', nodecl> end
function tico.tileset_load(path: cstring, image: *tc_Image): tc_Tileset <cimport'tico_tileset_load', nodecl> end
function tico.tileset_from_json(tileset: *tc_Tileset, json: *cJSON): cint <cimport'tico_tileset_from_json', nodecl> end
function tico.tileset_destroy(tileset: *tc_Tileset) <cimport'tico_tileset_destroy', nodecl> end
function tico.tileset_set_bitmask(tileset: *tc_Tileset, index: cint, bitmask: cint) <cimport'tico_tileset_set_bitmask', nodecl> end
function tico.tileset_calc_mask_array(tileset: tc_Tileset, bitmask: cint, bitmask_array: *cint) <cimport'tico_tileset_calc_mask_array', nodecl> end
function tico.tileset_calc_mask(tileset: tc_Tileset, bitmask_array: *cint): cint <cimport'tico_tileset_calc_mask', nodecl> end
function tico.tileset_draw(tileset: tc_Tileset, index: cint, x: cint, y: cint, color: tc_Color) <cimport'tico_tileset_draw', nodecl> end
function tico.tileset_get_rect(tileset: tc_Tileset, index: cint): tc_Rectf <cimport'tico_tileset_get_rect', nodecl> end
function tico.tileset_get_from_bitmask(tileset: tc_Tileset, bitmask: cint): cint <cimport'tico_tileset_get_from_bitmask', nodecl> end
function tico.tilemap_create(tileset: *tc_Tileset, w: cint, h: cint): tc_Tilemap <cimport'tico_tilemap_create', nodecl> end
function tico.tilemap_load(path: cstring, tileset: *tc_Tileset): tc_Tilemap <cimport'tico_tilemap_load', nodecl> end
function tico.tilemap_from_json(tilemap: *tc_Tilemap, json: *cJSON): cint <cimport'tico_tilemap_from_json', nodecl> end
function tico.tilemap_resize(tilemap: *tc_Tilemap, w: cint, h: cint) <cimport'tico_tilemap_resize', nodecl> end
function tico.tilemap_destroy(map: *tc_Tilemap) <cimport'tico_tilemap_destroy', nodecl> end
function tico.tilemap_has_tile(map: tc_Tilemap, x: cint, y: cint): cint <cimport'tico_tilemap_has_tile', nodecl> end
function tico.tilemap_draw(map: tc_Tilemap) <cimport'tico_tilemap_draw', nodecl> end
function tico.tilemap_draw_part(map: tc_Tilemap, part: tc_Rect, x: cint, y: cint) <cimport'tico_tilemap_draw_part', nodecl> end
function tico.tilemap_update(map: *tc_Tilemap) <cimport'tico_tilemap_update', nodecl> end
function tico.tilemap_autotile(tilemap: tc_Tilemap, index: cint): cint <cimport'tico_tilemap_autotile', nodecl> end
function tico.tilemap_autotile_pos(tilemap: tc_Tilemap, x: cint, y: cint): cint <cimport'tico_tilemap_autotile_pos', nodecl> end
function tico.tilemap_insert(map: *tc_Tilemap, index: cint) <cimport'tico_tilemap_insert', nodecl> end
function tico.tilemap_remove(map: *tc_Tilemap, index: cint) <cimport'tico_tilemap_remove', nodecl> end
function tico.tilemap_insert_pos(map: *tc_Tilemap, index: cint) <cimport'tico_tilemap_insert_pos', nodecl> end
function tico.tilemap_get_index(map: tc_Tilemap, x: cint, y: cint): cint <cimport'tico_tilemap_get_index', nodecl> end
function tico.tilemap_get_position(map: tc_Tilemap, index: cint, v: *tc_Vec2) <cimport'tico_tilemap_get_position', nodecl> end
function tico.camera_create(x: float32, y: float32, w: float32, h: float32): tc_Camera <cimport'tico_camera_create', nodecl> end
function tico.camera_destroy(camera: *tc_Camera) <cimport'tico_camera_destroy', nodecl> end
function tico.camera_attach(camera: tc_Camera) <cimport'tico_camera_attach', nodecl> end
function tico.camera_detach() <cimport'tico_camera_detach', nodecl> end
function tico.camera_set_pos(camera: *tc_Camera, pos: tc_Vec2) <cimport'tico_camera_set_pos', nodecl> end
function tico.camera_set_scale(camera: *tc_Camera, scale: tc_Vec2) <cimport'tico_camera_set_scale', nodecl> end
function tico.camera_set_size(camera: *tc_Camera, size: tc_Vec2) <cimport'tico_camera_set_size', nodecl> end
function tico.camera_get_pos(camera: tc_Camera, pos: *tc_Vec2) <cimport'tico_camera_get_pos', nodecl> end
function tico.camera_get_scale(camera: tc_Camera, scale: *tc_Vec2) <cimport'tico_camera_get_scale', nodecl> end
function tico.camera_get_size(camera: tc_Camera, size: *tc_Vec2) <cimport'tico_camera_get_size', nodecl> end
function tico.sprite_create(image: *tc_Image, w: cint, h: cint): tc_Sprite <cimport'tico_sprite_create', nodecl> end
function tico.sprite_from_json(sprite: *tc_Sprite, json: *cJSON): cint <cimport'tico_sprite_from_json', nodecl> end
function tico.sprite_destroy(sprite: *tc_Sprite) <cimport'tico_sprite_destroy', nodecl> end
function tico.sprite_update(sprite: *tc_Sprite) <cimport'tico_sprite_update', nodecl> end
function tico.animation_create(from: cint, to: cint): tc_Animation <cimport'tico_animation_create', nodecl> end
function tico.sprite_add_animation(sprite: *tc_Sprite, name: cstring, from: cint, to: cint) <cimport'tico_sprite_add_animation', nodecl> end
function tico.sprite_play(sprite: *tc_Sprite, name: cstring) <cimport'tico_sprite_play', nodecl> end
function tico.sprite_stop(sprite: *tc_Sprite) <cimport'tico_sprite_stop', nodecl> end
function tico.sprite_get_animation(sprite: *tc_Sprite): cstring <cimport'tico_sprite_get_animation', nodecl> end
function tico.sprite_draw_frame(sprite: tc_Sprite, frame: cint, x: float32, y: float32, color: tc_Color) <cimport'tico_sprite_draw_frame', nodecl> end
function tico.sprite_draw_frame_scale(sprite: tc_Sprite, frame: cint, x: float32, y: float32, sx: float32, sy: float32, color: tc_Color) <cimport'tico_sprite_draw_frame_scale', nodecl> end
function tico.sprite_draw_frame_ex(sprite: tc_Sprite, frame: cint, x: float32, y: float32, angle: float32, sx: float32, sy: float32, cx: float32, cy: float32, color: tc_Color) <cimport'tico_sprite_draw_frame_ex', nodecl> end
function tico.sprite_draw(sprite: tc_Sprite, x: float32, y: float32, color: tc_Color) <cimport'tico_sprite_draw', nodecl> end
function tico.sprite_draw_scale(sprite: tc_Sprite, x: float32, y: float32, sx: float32, sy: float32, color: tc_Color) <cimport'tico_sprite_draw_scale', nodecl> end
function tico.sprite_draw_ex(sprite: tc_Sprite, x: float32, y: float32, angle: float32, sx: float32, sy: float32, cx: float32, cy: float32, color: tc_Color) <cimport'tico_sprite_draw_ex', nodecl> end
local tc_Timer: type <cimport, nodecl> = @record{
  currentTime: float64,
  lastTime: float64,
  fpsLastTime: float64,
  delta: float32,
  fps: cint,
  frames: cint
}
function tico.timer_init(timer: *tc_Timer): cint <cimport'tico_timer_init', nodecl> end
function tico.timer_terminate(timer: *tc_Timer) <cimport'tico_timer_terminate', nodecl> end
local tc_Plugin: type <cimport, nodecl> = @record{
  data: pointer,
  enable: function(pointer): cint --[[PluginEnable]],
  disable: function(pointer): cint --[[PluginDisable]],
  load: function(pointer): cint --[[PluginLoad]],
  update: function(pointer): cint --[[PluginUpdate]],
  pre_draw: function(pointer): cint --[[PluginPreDraw]],
  draw: function(pointer): cint --[[PluginDraw]],
  post_draw: function(pointer): cint --[[PluginPostDraw]],
  terminate: function(pointer): cint --[[PluginTerminate]]
}
local tc_PluginModule: type <cimport, nodecl> = @record{
  plugins: map_plugin_t,
  active_plugins: vec_str_t
}
function tico.plugin_create(): tc_Plugin <cimport'tico_plugin_create', nodecl> end
function tico.plugin_editor(): tc_Plugin <cimport'tico_plugin_editor', nodecl> end
function tico.plugin_lua(): tc_Plugin <cimport'tico_plugin_lua', nodecl> end
function tico.plugin_resource(): tc_Plugin <cimport'tico_plugin_resource', nodecl> end
function tico.plugin_destroy(plugin: *tc_Plugin): cint <cimport'tico_plugin_destroy', nodecl> end
function tico.plugin_enable(plugin: *tc_Plugin) <cimport'tico_plugin_enable', nodecl> end
function tico.plugin_disable(plugin: *tc_Plugin) <cimport'tico_plugin_disable', nodecl> end
function tico.plugin_update(plugin: *tc_Plugin) <cimport'tico_plugin_update', nodecl> end
function tico.plugin_begin_draw(plugin: *tc_Plugin) <cimport'tico_plugin_begin_draw', nodecl> end
function tico.plugin_draw(plugin: *tc_Plugin) <cimport'tico_plugin_draw', nodecl> end
function tico.plugin_end_draw(plugin: *tc_Plugin) <cimport'tico_plugin_end_draw', nodecl> end
local tc_Lua: type <cimport, nodecl> = @record{
  L: *lua_State
}
function tico.plugin_lua_load(lua: *tc_Lua): cint <cimport'tico_plugin_lua_load', nodecl> end
function tico.plugin_lua_update(lua: *tc_Lua): cint <cimport'tico_plugin_lua_update', nodecl> end
function tico.plugin_lua_draw(lua: *tc_Lua): cint <cimport'tico_plugin_lua_draw', nodecl> end
function tico.plugin_lua_get_state(): *lua_State <cimport'tico_plugin_lua_get_state', nodecl> end
function tico.plugin_lua_add_lib(name: cstring, Function: LuaFunction) <cimport'tico_plugin_lua_add_lib', nodecl> end
function tico.plugin_lua_pcall(name: cstring, n: cint) <cimport'tico_plugin_lua_pcall', nodecl> end
local tc_Resource: type <cimport, nodecl, forwarddecl> = @record{}
local tc_ResourceDep: type <cimport, nodecl, forwarddecl> = @record{}
local tc_ResourcePlugin: type <cimport, nodecl, forwarddecl> = @record{}
tc_ResourceDep = @record{
  name: [256]cchar,
  res_key: [256]cchar,
  res: *tc_Resource
}
local TIC_RESOURCE_ERROR: cint <comptime> = 1
local TIC_RESOURCE_LOADED: cint <comptime> = 2
local TIC_RESOURCE_MISSING_DEP: cint <comptime> = 4
local TIC_RESOURCE_CHANGED: cint <comptime> = 8
tc_Resource = @record{
  status: cint,
  changed: cint,
  type: [64]cchar,
  uuid: [9]cchar,
  name: [256]cchar,
  path: [256]cchar,
  data: pointer
}
local tc_ResourceManager: type <cimport, nodecl, forwarddecl> = @record{}
tc_ResourcePlugin = @record{
  loader: function(*tc_ResourceManager, *tc_Resource, *cJSON): tc_Resource --[[PluginResourceLoader]],
  store: function(*tc_ResourceManager, *tc_Resource): *cJSON --[[PluginResourceStore]]
}
function tico.plugin_resource_init(loader: function(*tc_ResourceManager, *tc_Resource, *cJSON): tc_Resource --[[PluginResourceLoader]], store: function(*tc_ResourceManager, *tc_Resource): *cJSON --[[PluginResourceStore]]): tc_ResourcePlugin <cimport'tico_plugin_resource_init', nodecl> end
function tico.plugin_resource_json(): tc_ResourcePlugin <cimport'tico_plugin_resource_json', nodecl> end
function tico.plugin_resource_json_loader(manager: *tc_ResourceManager, res: *tc_Resource, json: *cJSON): tc_Resource <cimport'tico_plugin_resource_json_loader', nodecl> end
function tico.plugin_resource_json_store(manager: *tc_ResourceManager, res: *tc_Resource): *cJSON <cimport'tico_plugin_resource_json_store', nodecl> end
function tico.plugin_resource_image(): tc_ResourcePlugin <cimport'tico_plugin_resource_image', nodecl> end
function tico.plugin_resource_image_loader(manager: *tc_ResourceManager, res: *tc_Resource, json: *cJSON): tc_Resource <cimport'tico_plugin_resource_image_loader', nodecl> end
function tico.plugin_resource_image_store(manager: *tc_ResourceManager, res: *tc_Resource): *cJSON <cimport'tico_plugin_resource_image_store', nodecl> end
function tico.plugin_resource_sprite(): tc_ResourcePlugin <cimport'tico_plugin_resource_sprite', nodecl> end
function tico.plugin_resource_sprite_loader(manager: *tc_ResourceManager, res: *tc_Resource, json: *cJSON): tc_Resource <cimport'tico_plugin_resource_sprite_loader', nodecl> end
function tico.plugin_resource_sprite_store(manager: *tc_ResourceManager, res: *tc_Resource): *cJSON <cimport'tico_plugin_resource_sprite_store', nodecl> end
function tico.plugin_resource_tileset(): tc_ResourcePlugin <cimport'tico_plugin_resource_tileset', nodecl> end
function tico.plugin_resource_tileset_loader(manager: *tc_ResourceManager, res: *tc_Resource, json: *cJSON): tc_Resource <cimport'tico_plugin_resource_tileset_loader', nodecl> end
function tico.plugin_resource_tileset_store(manager: *tc_ResourceManager, res: *tc_Resource): *cJSON <cimport'tico_plugin_resource_tileset_store', nodecl> end
function tico.plugin_resource_tilemap(): tc_ResourcePlugin <cimport'tico_plugin_resource_tilemap', nodecl> end
function tico.plugin_resource_tilemap_loader(manager: *tc_ResourceManager, res: *tc_Resource, json: *cJSON): tc_Resource <cimport'tico_plugin_resource_tilemap_loader', nodecl> end
function tico.plugin_resource_tilemap_store(manager: *tc_ResourceManager, res: *tc_Resource): *cJSON <cimport'tico_plugin_resource_tilemap_store', nodecl> end
function tico.plugin_resource_object(): tc_ResourcePlugin <cimport'tico_plugin_resource_object', nodecl> end
function tico.plugin_resource_object_loader(manager: *tc_ResourceManager, res: *tc_Resource, json: *cJSON): tc_Resource <cimport'tico_plugin_resource_object_loader', nodecl> end
function tico.plugin_resource_object_store(manager: *tc_ResourceManager, res: *tc_Resource): *cJSON <cimport'tico_plugin_resource_object_store', nodecl> end
tc_ResourceManager = @record{
  path: [256]cchar,
  resources: map_resource_t,
  plugins: map_resplugin_t,
  missing: map_str_t,
  keys: map_str_t,
  lua: *tc_Lua,
  fields: *tc_Field
}
function tico.resource_init(resource: *tc_Resource) <cimport'tico_resource_init', nodecl> end
function tico.resource_change_lua(resource: *tc_Resource): cint <cimport'tico_resource_change_lua', nodecl> end
function tico.plugin_resources_init(manager: *tc_ResourceManager): cint <cimport'tico_plugin_resources_init', nodecl> end
function tico.plugin_resources_default_loaders(manager: *tc_ResourceManager): cint <cimport'tico_plugin_resources_default_loaders', nodecl> end
function tico.plugin_resources_load(manager: *tc_ResourceManager, type: cstring, name: cstring, path: cstring): cint <cimport'tico_plugin_resources_load', nodecl> end
function tico.plugin_resources_from_json(manager: *tc_ResourceManager, json: *cJSON): *tc_Resource <cimport'tico_plugin_resources_from_json', nodecl> end
function tico.plugin_resources_destroy(manager: *tc_ResourceManager): cint <cimport'tico_plugin_resources_destroy', nodecl> end
function tico.plugin_resources_check_json_deps(manager: *tc_ResourceManager, json: *cJSON): cint <cimport'tico_plugin_resources_check_json_deps', nodecl> end
function tico.plugin_resources_update_missing(manager: *tc_ResourceManager) <cimport'tico_plugin_resources_update_missing', nodecl> end
function tico.plugin_resources_new_dep(name: cstring, res: *tc_Resource): tc_ResourceDep <cimport'tico_plugin_resources_new_dep', nodecl> end
function tico.plugin_resources_push_dep(res: *tc_Resource, name: cstring, resource_name: cstring) <cimport'tico_plugin_resources_push_dep', nodecl> end
function tico.plugin_resources_change_dep(manager: *tc_ResourceManager, name: cstring, res_name: cstring) <cimport'tico_plugin_resources_change_dep', nodecl> end
function tico.plugin_resources_new_type(manager: *tc_ResourceManager, type: cstring) <cimport'tico_plugin_resources_new_type', nodecl> end
function tico.plugin_resources_update_resource(resource: *tc_Resource) <cimport'tico_plugin_resources_update_resource', nodecl> end
function tico.plugin_resources_add(manager: *tc_ResourceManager, type: cstring, name: cstring, resource: *tc_Resource): cint <cimport'tico_plugin_resources_add', nodecl> end
function tico.plugin_resources_store(resource: *tc_Resource): cint <cimport'tico_plugin_resources_store', nodecl> end
function tico.plugin_resources_get_by_field(field: *tc_Field): *tc_Resource <cimport'tico_plugin_resources_get_by_field', nodecl> end
function tico.plugin_resources_get_by_key(key: cstring): *tc_Resource <cimport'tico_plugin_resources_get_by_key', nodecl> end
function tico.plugin_resources_get_by_uuid(uuid: cstring): *tc_Resource <cimport'tico_plugin_resources_get_by_uuid', nodecl> end
function tico.plugin_resources_get(type: cstring, name: cstring): *tc_Resource <cimport'tico_plugin_resources_get', nodecl> end
local tc_PanelWidget: type <cimport, nodecl> = @record{
  grid_size: cint,
  origin: tc_Vec2,
  cursor_pos: tc_Vec2,
  size: tc_Vec2,
  bg_canvas: tc_Canvas,
  bg_colors: [2]tc_Color,
  scale: float32,
  bg_color: cuint,
  line_color: cuint,
  cross_color: cuint
}
function tico.widget_panel_create(grid_size: cint): tc_PanelWidget <cimport'tico_widget_panel_create', nodecl> end
function tico.widget_panel_destroy(widget: *tc_PanelWidget) <cimport'tico_widget_panel_destroy', nodecl> end
function tico.widget_panel_origin(widget: *tc_PanelWidget, out: *tc_Vec2) <cimport'tico_widget_panel_origin', nodecl> end
function tico.widget_panel_begin(widget: *tc_PanelWidget): cint <cimport'tico_widget_panel_begin', nodecl> end
function tico.widget_panel_end(widget: *tc_PanelWidget) <cimport'tico_widget_panel_end', nodecl> end
local tc_GridWidget: type <cimport, nodecl> = @record{
  bg: tc_Canvas,
  grid: tc_Vec2,
  size: tc_Vec2,
  scrolling: tc_Vec2,
  texture: *tc_Texture,
  tex_uv: tc_Rectf,
  flags: cint,
  state: cint,
  mouse_grid: tc_Vec2,
  scale: cint,
  cell: cint
}
function tico.widget_grid_create(tile: tc_Vec2, size: tc_Vec2, flags: cint): tc_GridWidget <cimport'tico_widget_grid_create', nodecl> end
function tico.widget_grid_destroy(widget: *tc_GridWidget) <cimport'tico_widget_grid_destroy', nodecl> end
function tico.widget_grid_set_texture(widget: *tc_GridWidget, tex: *tc_Texture, tex_uv: tc_Rectf) <cimport'tico_widget_grid_set_texture', nodecl> end
function tico.widget_grid_update(widget: *tc_GridWidget, panel: *tc_PanelWidget): cint <cimport'tico_widget_grid_update', nodecl> end
function tico.widget_grid_draw(widget: *tc_GridWidget, panel: *tc_PanelWidget): cint <cimport'tico_widget_grid_draw', nodecl> end
local tc_Object: type <cimport, nodecl> = @record{
  data: *tc_Field
}
local tc_ObjectWidget: type <cimport, nodecl> = @record{
  selected: *tc_Object,
  uuid: [8]cchar,
  object_data: *tc_Field,
  objects: map_object_t,
  panel: tc_PanelWidget,
  flags: cint,
  last_x: cint,
  last_y: cint
}
function tico.object_create(type: cstring, position: tc_Vec2): tc_Object <cimport'tico_object_create', nodecl> end
function tico.object_from_json(json: *tc_Field): tc_Object <cimport'tico_object_from_json', nodecl> end
function tico.object_update(object: *tc_Object) <cimport'tico_object_update', nodecl> end
function tico.object_draw(object: *tc_Object, origin: tc_Vec2, scale: float32, selected: cint) <cimport'tico_object_draw', nodecl> end
function tico.object_is_hovered(object: *tc_Object, origin: tc_Vec2, scale: float32): boolean <cimport'tico_object_is_hovered', nodecl> end
function tico.widget_object_init(widget: *tc_ObjectWidget, data: *tc_Field): cint <cimport'tico_widget_object_init', nodecl> end
function tico.widget_object_deinit(widget: *tc_ObjectWidget) <cimport'tico_widget_object_deinit', nodecl> end
function tico.widget_object_update(widget: *tc_ObjectWidget, panel: *tc_PanelWidget): cint <cimport'tico_widget_object_update', nodecl> end
function tico.widget_object_draw(widget: *tc_ObjectWidget, panel: *tc_PanelWidget, active: *cint): cint <cimport'tico_widget_object_draw', nodecl> end
function tico.widget_object_edit(widget: *tc_ObjectWidget, object: *tc_Object): cint <cimport'tico_widget_object_edit', nodecl> end
function tico.widget_object_selected(widget: *tc_ObjectWidget, object: *tc_Object, origin: tc_Vec2, scale: float32): cint <cimport'tico_widget_object_selected', nodecl> end
function tico.widget_object_resized(widget: *tc_ObjectWidget, object: *tc_Object): cint <cimport'tico_widget_object_resized', nodecl> end
local tc_EditorFolder: type <cimport, nodecl, forwarddecl> = @record{}
local tc_EditorWindow: type <cimport, nodecl, forwarddecl> = @record{}
local tc_GridTool: type <cimport, nodecl> = @record{
  camera: tc_Camera,
  canvas: tc_Canvas,
  bg: tc_Canvas,
  grid: tc_Vec2,
  size: tc_Vec2,
  scrolling: tc_Vec2,
  scale: cint
}
tc_EditorFolder = @record{
  name: [64]cchar,
  child: *tc_EditorFolder,
  next: *tc_EditorFolder,
  res: list_str_t
}
local tc_EditorPlugin: type <cimport, nodecl> = @record{
  editor: pointer,
  size: cint,
  create: function(pointer): cint --[[EditorPluginUpdate]],
  init: function(pointer, *tc_EditorWindow): cint --[[EditorPluginInit]],
  update: function(pointer): cint --[[EditorPluginUpdate]],
  draw: function(pointer): cint --[[EditorPluginUpdate]],
  draw_panel: function(pointer): cint --[[EditorPluginUpdate]],
  destroy: function(pointer): cint --[[EditorPluginUpdate]],
  save: function(pointer): cint --[[EditorPluginUpdate]]
}
tc_EditorWindow = @record{
  title: [128]cchar,
  open: cint,
  res: *tc_Resource,
  editor: pointer,
  flags: cint,
  plugin: tc_EditorPlugin
}
local tc_Editor: type <cimport, nodecl> = @record{
  size: cint,
  game_canvas: tc_Canvas,
  manager: *tc_ResourceManager,
  lua: *tc_Lua,
  plugins: map_editorplugin_t,
  windows: map_int_t,
  folders: *tc_Field,
  paused: cint,
  plugins_window: cint,
  imgui_demo: cint,
  window_pool: [32]tc_EditorWindow,
  current_window: *tc_EditorWindow
}
function tico.plugin_editor_create(init: function(pointer, *tc_EditorWindow): cint --[[EditorPluginInit]], update: function(pointer): cint --[[EditorPluginUpdate]], draw: function(pointer): cint --[[EditorPluginUpdate]], draw_panel: function(pointer): cint --[[EditorPluginUpdate]]): tc_EditorPlugin <cimport'tico_plugin_editor_create', nodecl> end
function tico.plugin_editor_load(editor: *tc_Editor): cint <cimport'tico_plugin_editor_load', nodecl> end
function tico.plugin_editor_update(editor: *tc_Editor): cint <cimport'tico_plugin_editor_update', nodecl> end
function tico.plugin_editor_draw(editor: *tc_Editor): cint <cimport'tico_plugin_editor_draw', nodecl> end
function tico.plugin_editor_add_plugin(editor: *tc_Editor, type: cstring, plugin: *tc_EditorPlugin): cint <cimport'tico_plugin_editor_add_plugin', nodecl> end
function tico.plugin_editor_open(uuid: cstring): cint <cimport'tico_plugin_editor_open', nodecl> end
function tico.editor_set_bg(canvas: tc_Canvas, size: cint, col1: tc_Color, col2: tc_Color) <cimport'tico_editor_set_bg', nodecl> end
function tico.editor_init_window(window: *tc_EditorWindow, plugin: *tc_EditorPlugin) <cimport'tico_editor_init_window', nodecl> end
function tico.editor_destroy_window(window: *tc_EditorWindow) <cimport'tico_editor_destroy_window', nodecl> end
function tico.editor_draw_window(window: *tc_EditorWindow): cint <cimport'tico_editor_draw_window', nodecl> end
function tico.editor_draw_window_panel(window: *tc_EditorWindow) <cimport'tico_editor_draw_window_panel', nodecl> end
local TIC_AUDIO_USAGE_: type <cimport, nodecl, using> = @enum(cint){
  AUDIO_STREAM = 0,
  AUDIO_STATIC = 1
}
local tc_AudioData: type <cimport, nodecl> = @record{
  usage: TIC_AUDIO_USAGE_,
  data: *cuchar,
  filename: *cuchar,
  size: csize,
  refs: cint
}
local tc_AudioBuffer: type <cimport, nodecl> = @record{
  decoder: ma_decoder,
  id: cuchar,
  volume: float32,
  pitch: float32,
  playing: cint,
  paused: cint,
  loop: cint,
  loaded: cint,
  data: *tc_AudioData,
  currentReadPos: csize
}
local tc_Sound: type <cimport, nodecl> = @record{
  audioBuffer: *tc_AudioBuffer
}
function tico.audio_init(): cint <cimport'tico_audio_init', nodecl> end
function tico.audio_start_device(): cint <cimport'tico_audio_start_device', nodecl> end
function tico.audio_stop_device(): cint <cimport'tico_audio_stop_device', nodecl> end
function tico.audio_terminate() <cimport'tico_audio_terminate', nodecl> end
function tico.audio_set_master_volume(volume: float32) <cimport'tico_audio_set_master_volume', nodecl> end
function tico.audio_get_id(buffer: *tc_AudioBuffer): cint <cimport'tico_audio_get_id', nodecl> end
function tico.audio_get_from_id(id: cuint): *tc_AudioBuffer <cimport'tico_audio_get_from_id', nodecl> end
function tico.buffer_load(filename: cstring, usage: TIC_AUDIO_USAGE_): *tc_AudioBuffer <cimport'tico_buffer_load', nodecl> end
function tico.buffer_play(audioBuffer: *tc_AudioBuffer) <cimport'tico_buffer_play', nodecl> end
function tico.buffer_stop(audioBuffer: *tc_AudioBuffer) <cimport'tico_buffer_stop', nodecl> end
function tico.buffer_pause(audioBuffer: *tc_AudioBuffer) <cimport'tico_buffer_pause', nodecl> end
function tico.buffer_unload(audioBuffer: *tc_AudioBuffer) <cimport'tico_buffer_unload', nodecl> end
function tico.buffer_is_playing(audioBuffer: *tc_AudioBuffer): boolean <cimport'tico_buffer_is_playing', nodecl> end
function tico.buffer_is_paused(audioBuffer: *tc_AudioBuffer): boolean <cimport'tico_buffer_is_paused', nodecl> end
function tico.buffer_set_volume(audioBuffer: *tc_AudioBuffer, volume: float32) <cimport'tico_buffer_set_volume', nodecl> end
function tico.sound_load(filename: cstring, usage: TIC_AUDIO_USAGE_): tc_Sound <cimport'tico_sound_load', nodecl> end
function tico.sound_unload(sound: tc_Sound) <cimport'tico_sound_unload', nodecl> end
function tico.sound_play(sound: tc_Sound) <cimport'tico_sound_play', nodecl> end
function tico.sound_stop(sound: tc_Sound) <cimport'tico_sound_stop', nodecl> end
function tico.sound_pause(sound: tc_Sound) <cimport'tico_sound_pause', nodecl> end
function tico.sound_is_playing(sound: tc_Sound): boolean <cimport'tico_sound_is_playing', nodecl> end
function tico.sound_is_paused(sound: tc_Sound): boolean <cimport'tico_sound_is_paused', nodecl> end
function tico.sound_set_volume(sound: tc_Sound, volume: float32) <cimport'tico_sound_set_volume', nodecl> end
function tico.audio_data_free(data: *tc_AudioData) <cimport'tico_audio_data_free', nodecl> end
local TIC_DRAW_MODE_: type <cimport, nodecl, using> = @enum(cint){
  TRIANGLES = 0,
  LINES = 1
}
local TIC_FRAGMENT_SHADERS_: type <cimport, nodecl, using> = @enum(cint){
  DEFAULT_FRAGMENT = 0,
  GBA_FRAG_SHADER = 1,
  COLOR8_FRAG_SHADER = 2,
  COLOR16_FRAG_SHADER = 3,
  OUTLINE_FRAG_SHADER = 4
}
local TIC_VERTEX_SHADERS_: type <cimport, nodecl, using> = @enum(cint){
  DEFAULT_VERTEX = 0
}
local tc_Vertex: type <cimport, nodecl> = @record{
  pos: [2]float32,
  color: [4]float32,
  uv: [2]float32
}
local tc_DrawCall: type <cimport, nodecl> = @record{
  indexStart: cuint,
  indexCount: cuint,
  vertexCount: cuint,
  mode: TIC_DRAW_MODE_,
  textureId: cuint,
  modelview: tc_Matrix,
  clip: tc_Rect
}
local tc_Batch: type <cimport, nodecl> = @record{
  indices: *cuint,
  vertices: *tc_Vertex,
  verticesPtr: *tc_Vertex,
  drawCalls: [128]tc_DrawCall,
  drawCallIndex: cuint,
  totalIndexCount: cuint,
  totalVertexCount: cuint,
  maxQuads: cuint,
  maxVertices: cuint,
  maxIndices: cuint,
  vao: cuint,
  vbo: [2]cuint,
  currentClip: tc_Rect,
  currentTexture: tc_Texture
}
local tc_Render: type <cimport, nodecl> = @record{
  batch: tc_Batch,
  state: record{
    defaultShader: tc_Shader,
    currentShader: tc_Shader,
    canvasIndex: cint,
    shaderIndex: cint,
    vertexShaders: [32]cint,
    fragmentShaders: [32]cint,
    defaultVertexShader: cint,
    defaultFragmentShader: cint,
    defaultTextureId: cuint,
    currentTextureId: cuint,
    shapeTexture: tc_Texture,
    drawCount: cuint,
    currentCanvas: tc_Canvas,
    modelview: tc_Matrix,
    defaultCanvas: tc_Canvas,
    camera: *tc_Matrix,
    currentMatrix: cint,
    backToDefaultCanvas: function(pointer)
  }
}
function tico.render_init(render: *tc_Render): cint <cimport'tico_render_init', nodecl> end
function tico.render_terminate(render: *tc_Render) <cimport'tico_render_terminate', nodecl> end
function tico.render_push_canvas(canvas: tc_Canvas) <cimport'tico_render_push_canvas', nodecl> end
function tico.render_pop_canvas() <cimport'tico_render_pop_canvas', nodecl> end
function tico.render_push_shader(shader: tc_Shader) <cimport'tico_render_push_shader', nodecl> end
function tico.render_pop_shader() <cimport'tico_render_pop_shader', nodecl> end
function tico.render_set_texture(render: *tc_Render, texture: tc_Texture) <cimport'tico_render_set_texture', nodecl> end
function tico.render_set_clip(render: *tc_Render, rect: tc_Rect) <cimport'tico_render_set_clip', nodecl> end
function tico.render_set_draw_mode(render: *tc_Render, mode: TIC_DRAW_MODE_) <cimport'tico_render_set_draw_mode', nodecl> end
function tico.render_set_transform(render: *tc_Render, matrix: tc_Matrix) <cimport'tico_render_set_transform', nodecl> end
function tico.render_align(render: *tc_Render) <cimport'tico_render_align', nodecl> end
function tico.render_update_count(render: *tc_Render, indexCount: cint, vertexCount: cint) <cimport'tico_render_update_count', nodecl> end
function tico.render_add_rect(render: *tc_Render, dest: tc_Rectf, source: tc_Rectf, color: tc_Color) <cimport'tico_render_add_rect', nodecl> end
function tico.render_add_rect_ex(render: *tc_Render, dest: tc_Rectf, source: tc_Rectf, angle: float32, origin: tc_Vec2, color: tc_Color) <cimport'tico_render_add_rect_ex', nodecl> end
function tico.render_add_triangle(render: *tc_Render, p0: tc_Vec2, p1: tc_Vec2, p2: tc_Vec2, color: tc_Color) <cimport'tico_render_add_triangle', nodecl> end
function tico.render_add_circle(render: *tc_Render, p: tc_Vec2, radius: float32, sides: cint, color: tc_Color) <cimport'tico_render_add_circle', nodecl> end
function tico.render_add_line(render: *tc_Render, p0: tc_Vec2, p1: tc_Vec2, color: tc_Color) <cimport'tico_render_add_line', nodecl> end
function tico.render_begin(render: *tc_Render) <cimport'tico_render_begin', nodecl> end
function tico.render_flush(render: *tc_Render) <cimport'tico_render_flush', nodecl> end
function tico.render_draw(render: *tc_Render) <cimport'tico_render_draw', nodecl> end
function tico.render_clear(render: *tc_Render) <cimport'tico_render_clear', nodecl> end
function tico.render_is_empty(render: *tc_Render): boolean <cimport'tico_render_is_empty', nodecl> end
function tico.render_is_full(render: *tc_Render, vertices: cint): boolean <cimport'tico_render_is_full', nodecl> end
function tico.render_draw_reset(render: *tc_Render) <cimport'tico_render_draw_reset', nodecl> end
function tico.render_reset_if_full(render: *tc_Render, vertex: cint) <cimport'tico_render_reset_if_full', nodecl> end
function tico.drawcall_create(start: cint, texture: cint, mode: TIC_DRAW_MODE_, clip: *tc_Rect, modelview: tc_Matrix): tc_DrawCall <cimport'tico_drawcall_create', nodecl> end
function tico.drawcall_destroy(call: *tc_DrawCall) <cimport'tico_drawcall_destroy', nodecl> end
function tico.batch_create(texture: tc_Texture, maxQuads: cint): tc_Batch <cimport'tico_batch_create', nodecl> end
function tico.batch_destroy(batch: *tc_Batch) <cimport'tico_batch_destroy', nodecl> end
function tico.batch_get_transform(batch: *tc_Batch): *tc_Matrix <cimport'tico_batch_get_transform', nodecl> end
function tico.batch_next_drawcall(batch: *tc_Batch, inv: cint): *tc_DrawCall <cimport'tico_batch_next_drawcall', nodecl> end
function tico.batch_set_texture(batch: *tc_Batch, texture: tc_Texture) <cimport'tico_batch_set_texture', nodecl> end
function tico.batch_set_clip(batch: *tc_Batch, rect: tc_Rect) <cimport'tico_batch_set_clip', nodecl> end
function tico.batch_set_draw_mode(batch: *tc_Batch, mode: TIC_DRAW_MODE_) <cimport'tico_batch_set_draw_mode', nodecl> end
function tico.batch_set_transform(batch: *tc_Batch, matrix: tc_Matrix) <cimport'tico_batch_set_transform', nodecl> end
function tico.batch_align(batch: *tc_Batch) <cimport'tico_batch_align', nodecl> end
function tico.batch_update_count(batch: *tc_Batch, indexCount: cint, vertexCount: cint) <cimport'tico_batch_update_count', nodecl> end
function tico.batch_add_rect(batch: *tc_Batch, dest: tc_Rectf, source: tc_Rectf, color: tc_Color) <cimport'tico_batch_add_rect', nodecl> end
function tico.batch_add_line_rect(batch: *tc_Batch, dest: tc_Rectf, src: tc_Rectf, color: tc_Color) <cimport'tico_batch_add_line_rect', nodecl> end
function tico.batch_add_rect_ex(batch: *tc_Batch, dest: tc_Rectf, source: tc_Rectf, angle: float32, cx: float32, cy: float32, color: tc_Color) <cimport'tico_batch_add_rect_ex', nodecl> end
function tico.batch_add_triangle(batch: *tc_Batch, x0: cint, y0: cint, x1: cint, y1: cint, x2: cint, y2: cint, color: tc_Color) <cimport'tico_batch_add_triangle', nodecl> end
function tico.batch_add_circle(batch: *tc_Batch, x: cint, y: cint, radius: float32, sides: cint, color: tc_Color) <cimport'tico_batch_add_circle', nodecl> end
function tico.batch_add_line(batch: *tc_Batch, x0: cint, y0: cint, x1: cint, y1: cint, color: tc_Color) <cimport'tico_batch_add_line', nodecl> end
function tico.batch_begin(batch: *tc_Batch) <cimport'tico_batch_begin', nodecl> end
function tico.batch_flush(batch: *tc_Batch) <cimport'tico_batch_flush', nodecl> end
function tico.batch_draw(batch: *tc_Batch) <cimport'tico_batch_draw', nodecl> end
function tico.batch_clear(batch: *tc_Batch) <cimport'tico_batch_clear', nodecl> end
function tico.batch_is_empty(batch: tc_Batch): boolean <cimport'tico_batch_is_empty', nodecl> end
function tico.batch_is_full(batch: tc_Batch, vertices: cint): boolean <cimport'tico_batch_is_full', nodecl> end
function tico.batch_draw_reset(batch: *tc_Batch) <cimport'tico_batch_draw_reset', nodecl> end
function tico.batch_reset_if_full(batch: *tc_Batch, vertex: cint) <cimport'tico_batch_reset_if_full', nodecl> end
local tc_Graphics: type <cimport, nodecl> = @record{
  default_font: tc_Font,
  canvas_stack: stack_canvas_t,
  shader_stack: stack_shader_t,
  matrix_stack: stack_matrix_t,
  canvas_vec: vec_canvas_t,
  render: tc_Render,
  default_texture: tc_Texture,
  default_vertex: cint,
  default_fragment: cint,
  default_shader: tc_Shader
}
function tico.graphics_init(graphics: *tc_Graphics): cint <cimport'tico_graphics_init', nodecl> end
function tico.graphics_terminate(graphics: *tc_Graphics) <cimport'tico_graphics_terminate', nodecl> end
function tico.texture_create(data: pointer, width: cint, height: cint, mode: cint): tc_Texture <cimport'tico_texture_create', nodecl> end
function tico.texture_load(filename: cstring): tc_Texture <cimport'tico_texture_load', nodecl> end
function tico.texture_from_memory(data: pointer, bufSize: cint): tc_Texture <cimport'tico_texture_from_memory', nodecl> end
function tico.texture_destroy(texture: *tc_Texture) <cimport'tico_texture_destroy', nodecl> end
function tico.texture_get_width(texture: tc_Texture): cint <cimport'tico_texture_get_width', nodecl> end
function tico.texture_get_height(texture: tc_Texture): cint <cimport'tico_texture_get_height', nodecl> end
function tico.texture_get_size(texture: tc_Texture, width: *cint, height: *cint) <cimport'tico_texture_get_size', nodecl> end
function tico.texture_set_filter(texture: *tc_Texture, min: cint, mag: cint) <cimport'tico_texture_set_filter', nodecl> end
function tico.texture_set_wrap(texture: *tc_Texture, min: cint, mag: cint) <cimport'tico_texture_set_wrap', nodecl> end
function tico.texture_get_filter(texture: tc_Texture, min: *cint, mag: *cint) <cimport'tico_texture_get_filter', nodecl> end
function tico.texture_get_wrap(texture: tc_Texture, min: *cint, mag: *cint) <cimport'tico_texture_get_wrap', nodecl> end
function tico.texture_draw(texture: tc_Texture, dest: tc_Rectf, source: tc_Rectf, color: tc_Color) <cimport'tico_texture_draw', nodecl> end
function tico.texture_draw_ex(texture: tc_Texture, dest: tc_Rectf, source: tc_Rectf, angle: float32, origin: tc_Vec2, color: tc_Color) <cimport'tico_texture_draw_ex', nodecl> end
function tico.image_create(data: pointer, width: cint, height: cint, mode: cint): tc_Image <cimport'tico_image_create', nodecl> end
function tico.image_load(image: cstring): tc_Image <cimport'tico_image_load', nodecl> end
function tico.image_from_memory(data: pointer, bufSize: cint): tc_Image <cimport'tico_image_from_memory', nodecl> end
function tico.image_destroy(image: *tc_Image) <cimport'tico_image_destroy', nodecl> end
function tico.image_get_width(image: tc_Image): cint <cimport'tico_image_get_width', nodecl> end
function tico.image_get_height(image: tc_Image): cint <cimport'tico_image_get_height', nodecl> end
function tico.image_get_size(image: tc_Image, width: *cint, height: *cint) <cimport'tico_image_get_size', nodecl> end
function tico.image_set_filter(image: *tc_Image, min: cint, mag: cint) <cimport'tico_image_set_filter', nodecl> end
function tico.image_get_filter(image: tc_Image, min: *cint, mag: *cint) <cimport'tico_image_get_filter', nodecl> end
function tico.image_set_wrap(image: *tc_Image, min: cint, mag: cint) <cimport'tico_image_set_wrap', nodecl> end
function tico.image_get_wrap(image: tc_Image, min: *cint, mag: *cint) <cimport'tico_image_get_wrap', nodecl> end
function tico.image_draw(image: tc_Image, x: float32, y: float32, color: tc_Color) <cimport'tico_image_draw', nodecl> end
function tico.image_draw_scale(image: tc_Image, x: float32, y: float32, sx: float32, sy: float32, color: tc_Color) <cimport'tico_image_draw_scale', nodecl> end
function tico.image_draw_ex(image: tc_Image, x: float32, y: float32, angle: float32, sx: float32, sy: float32, cx: float32, cy: float32, color: tc_Color) <cimport'tico_image_draw_ex', nodecl> end
function tico.image_draw_part(image: tc_Image, part: tc_Rectf, x: float32, y: float32, color: tc_Color) <cimport'tico_image_draw_part', nodecl> end
function tico.image_draw_part_scale(image: tc_Image, part: tc_Rectf, x: float32, y: float32, sx: float32, sy: float32, color: tc_Color) <cimport'tico_image_draw_part_scale', nodecl> end
function tico.image_draw_part_ex(image: tc_Image, part: tc_Rectf, x: float32, y: float32, angle: float32, sx: float32, sy: float32, cx: float32, cy: float32, color: tc_Color) <cimport'tico_image_draw_part_ex', nodecl> end
function tico.canvas_create(width: cint, height: cint): tc_Canvas <cimport'tico_canvas_create', nodecl> end
function tico.canvas_destroy(canvas: *tc_Canvas) <cimport'tico_canvas_destroy', nodecl> end
function tico.canvas_get_width(canvas: tc_Canvas): cint <cimport'tico_canvas_get_width', nodecl> end
function tico.canvas_get_height(canvas: tc_Canvas): cint <cimport'tico_canvas_get_height', nodecl> end
function tico.canvas_get_size(canvas: tc_Canvas, width: *cint, height: *cint) <cimport'tico_canvas_get_size', nodecl> end
function tico.canvas_attach(canvas: tc_Canvas) <cimport'tico_canvas_attach', nodecl> end
function tico.canvas_detach() <cimport'tico_canvas_detach', nodecl> end
function tico.canvas_disable() <cimport'tico_canvas_disable', nodecl> end
function tico.canvas_draw(canvas: tc_Canvas, x: float32, y: float32, color: tc_Color) <cimport'tico_canvas_draw', nodecl> end
function tico.canvas_draw_scale(canvas: tc_Canvas, x: float32, y: float32, sx: float32, sy: float32, color: tc_Color) <cimport'tico_canvas_draw_scale', nodecl> end
function tico.canvas_draw_ex(canvas: tc_Canvas, x: float32, y: float32, angle: float32, sx: float32, sy: float32, cx: float32, cy: float32, color: tc_Color) <cimport'tico_canvas_draw_ex', nodecl> end
function tico.canvas_draw_part(canvas: tc_Canvas, rect: tc_Rectf, x: float32, y: float32, color: tc_Color) <cimport'tico_canvas_draw_part', nodecl> end
function tico.canvas_draw_part_scale(canvas: tc_Canvas, rect: tc_Rectf, x: float32, y: float32, sx: float32, sy: float32, color: tc_Color) <cimport'tico_canvas_draw_part_scale', nodecl> end
function tico.canvas_draw_part_ex(canvas: tc_Canvas, rect: tc_Rectf, x: float32, y: float32, angle: float32, sx: float32, sy: float32, cx: float32, cy: float32, color: tc_Color) <cimport'tico_canvas_draw_part_ex', nodecl> end
function tico.canvas_draw_auto(canvas: tc_Canvas) <cimport'tico_canvas_draw_auto', nodecl> end
function tico.shader_create(vertShader: cint, fragShader: cint): tc_Shader <cimport'tico_shader_create', nodecl> end
function tico.shader_create_from_string(vertSource: cstring, fragSource: cstring): tc_Shader <cimport'tico_shader_create_from_string', nodecl> end
function tico.shader_create_from_ustring(source: cstring): tc_Shader <cimport'tico_shader_create_from_ustring', nodecl> end
function tico.shader_create_from_file(filename: cstring): tc_Shader <cimport'tico_shader_create_from_file', nodecl> end
function tico.shader_load_default(vertexShader: *cint, fragShader: *cint): tc_Shader <cimport'tico_shader_load_default', nodecl> end
function tico.shader_create_effect(vertEffect: cstring, fragEffect: cstring): tc_Shader <cimport'tico_shader_create_effect', nodecl> end
function tico.shader_destroy(shader: *tc_Shader) <cimport'tico_shader_destroy', nodecl> end
function tico.shader_compile(source: cstring, shaderType: cint): cint <cimport'tico_shader_compile', nodecl> end
function tico.shader_load_program(vertexShader: cint, fragShader: cint): cint <cimport'tico_shader_load_program', nodecl> end
function tico.shader_send_world(shader: tc_Shader) <cimport'tico_shader_send_world', nodecl> end
function tico.shader_send(shader: tc_Shader, name: cstring, data: pointer, type: TIC_SHADER_UNIFORM_) <cimport'tico_shader_send', nodecl> end
function tico.shader_send_count(shader: tc_Shader, name: cstring, count: cint, data: pointer, type: TIC_SHADER_UNIFORM_) <cimport'tico_shader_send_count', nodecl> end
function tico.shader_attach(shader: tc_Shader) <cimport'tico_shader_attach', nodecl> end
function tico.shader_detach() <cimport'tico_shader_detach', nodecl> end
function tico.font_load_default(): tc_Font <cimport'tico_font_load_default', nodecl> end
function tico.font_init(font: *tc_Font, data: pointer, bufSize: csize, fontSize: cint) <cimport'tico_font_init', nodecl> end
function tico.font_load(filename: cstring, size: cint): tc_Font <cimport'tico_font_load', nodecl> end
function tico.font_load_from_memory(data: pointer, bufSize: csize, fontSize: cint): tc_Font <cimport'tico_font_load_from_memory', nodecl> end
function tico.font_load_from_texture(texture: tc_Texture, fontWidth: cint, fontHeight: cint): tc_Font <cimport'tico_font_load_from_texture', nodecl> end
function tico.font_destroy(font: *tc_Font) <cimport'tico_font_destroy', nodecl> end
function tico.font_get_rect(font: tc_Font, c: cint, x: *float32, y: *float32, outPos: *tc_Vec2, rect: *tc_Rectf, width: cint) <cimport'tico_font_get_rect', nodecl> end
function tico.font_get_rect_scale(font: tc_Font, c: cint, x: *float32, y: *float32, outPos: *tc_Vec2, rect: *tc_Rectf, sx: float32, sy: float32, width: cint) <cimport'tico_font_get_rect_scale', nodecl> end
function tico.font_get_text_width(font: tc_Font, text: cstring, len: cint): cint <cimport'tico_font_get_text_width', nodecl> end
function tico.font_get_text_height(font: tc_Font, text: cstring, len: cint): cint <cimport'tico_font_get_text_height', nodecl> end
local TIC_WindowFlags_: type <cimport, nodecl, using> = @enum(cint){
  WindowFlags_Default = 0,
  WindowFlags_FullScreen = 1,
  WindowFlags_Resizable = 2,
  WindowFlags_VSync = 4
}
local TIC_CURSOR_ARROW: cint <comptime> = 0
local TIC_CURSOR_TEXT: cint <comptime> = 1
local TIC_CURSOR_CROSSHAIR: cint <comptime> = 2
local TIC_CURSOR_HAND: cint <comptime> = 3
local TIC_CURSOR_HRESIZE: cint <comptime> = 4
local TIC_CURSOR_VRESIZE: cint <comptime> = 5
local tc_Window: type <cimport, nodecl> = @record{
  title: [256]cchar,
  x: cint,
  y: cint,
  width: cint,
  height: cint,
  bkpMode: tc_Rect,
  mouse_cursors: [6]*GLFWcursor,
  state: record{
    fullscreen: cint,
    resizable: cint,
    vsync: cint
  },
  handle: pointer
}
function tico.window_init(window: *tc_Window, title: cstring, width: cint, height: cint, flags: TIC_WindowFlags_): cint <cimport'tico_window_init', nodecl> end
function tico.window_deinit(window: *tc_Window): cint <cimport'tico_window_deinit', nodecl> end
local TIC_KEY_: type <cimport, nodecl, using> = @enum(cint){
  KEY_UNKNOWN = -1,
  KEY_SPACE = 32,
  KEY_APOSTROPHE = 39,
  KEY_COMMA = 44,
  KEY_MINUS = 45,
  KEY_PERIOD = 46,
  KEY_SLASH = 47,
  KEY_0 = 48,
  KEY_1 = 49,
  KEY_2 = 50,
  KEY_3 = 51,
  KEY_4 = 52,
  KEY_5 = 53,
  KEY_6 = 54,
  KEY_7 = 55,
  KEY_8 = 56,
  KEY_9 = 57,
  KEY_SEMICOLON = 59,
  KEY_EQUAL = 61,
  KEY_A = 65,
  KEY_B = 66,
  KEY_C = 67,
  KEY_D = 68,
  KEY_E = 69,
  KEY_F = 70,
  KEY_G = 71,
  KEY_H = 72,
  KEY_I = 73,
  KEY_J = 74,
  KEY_K = 75,
  KEY_L = 76,
  KEY_M = 77,
  KEY_N = 78,
  KEY_O = 79,
  KEY_P = 80,
  KEY_Q = 81,
  KEY_R = 82,
  KEY_S = 83,
  KEY_T = 84,
  KEY_U = 85,
  KEY_V = 86,
  KEY_W = 87,
  KEY_X = 88,
  KEY_Y = 89,
  KEY_Z = 90,
  KEY_LEFT_BRACKET = 91,
  KEY_BACKSLASH = 92,
  KEY_RIGHT_BRACKET = 93,
  KEY_GRAVE_ACCENT = 96,
  KEY_WORLD_1 = 161,
  KEY_WORLD_2 = 162,
  KEY_ESCAPE = 256,
  KEY_ENTER = 257,
  KEY_TAB = 258,
  KEY_BACKSPACE = 259,
  KEY_INSERT = 260,
  KEY_DELETE = 261,
  KEY_RIGHT = 262,
  KEY_LEFT = 263,
  KEY_DOWN = 264,
  KEY_UP = 265,
  KEY_PAGE_UP = 266,
  KEY_PAGE_DOWN = 267,
  KEY_HOME = 268,
  KEY_END = 269,
  KEY_CAPS_LOCK = 280,
  KEY_SCROLL_LOCK = 281,
  KEY_NUM_LOCK = 282,
  KEY_PRINT_SCREEN = 283,
  KEY_PAUSE = 284,
  KEY_F1 = 290,
  KEY_F2 = 291,
  KEY_F3 = 292,
  KEY_F4 = 293,
  KEY_F5 = 294,
  KEY_F6 = 295,
  KEY_F7 = 296,
  KEY_F8 = 297,
  KEY_F9 = 298,
  KEY_F10 = 299,
  KEY_F11 = 300,
  KEY_F12 = 301,
  KEY_F13 = 302,
  KEY_F14 = 303,
  KEY_F15 = 304,
  KEY_F16 = 305,
  KEY_F17 = 306,
  KEY_F18 = 307,
  KEY_F19 = 308,
  KEY_F20 = 309,
  KEY_F21 = 310,
  KEY_F22 = 311,
  KEY_F23 = 312,
  KEY_F24 = 313,
  KEY_F25 = 314,
  KEY_KP_0 = 320,
  KEY_KP_1 = 321,
  KEY_KP_2 = 322,
  KEY_KP_3 = 323,
  KEY_KP_4 = 324,
  KEY_KP_5 = 325,
  KEY_KP_6 = 326,
  KEY_KP_7 = 327,
  KEY_KP_8 = 328,
  KEY_KP_9 = 329,
  KEY_KP_DECIMAL = 330,
  KEY_KP_DIVIDE = 331,
  KEY_KP_MULTIPLY = 332,
  KEY_KP_SUBTRACT = 333,
  KEY_KP_ADD = 334,
  KEY_KP_ENTER = 335,
  KEY_KP_EQUAL = 336,
  KEY_LEFT_SHIFT = 340,
  KEY_LEFT_CONTROL = 341,
  KEY_LEFT_ALT = 342,
  KEY_LEFT_SUPER = 343,
  KEY_RIGHT_SHIFT = 344,
  KEY_RIGHT_CONTROL = 345,
  KEY_RIGHT_ALT = 346,
  KEY_RIGHT_SUPER = 347,
  KEY_MENU = 348,
  KEY_LAST = 348,
  KEY_COUNT = 349
}
local TIC_MOUSEBUTTON_: type <cimport, nodecl, using> = @enum(cint){
  MOUSE_LEFT = 0,
  MOUSE_RIGHT = 1,
  MOUSE_MIDDLE = 2,
  MOUSE_BUTTON_LAST = 3,
  MOUSE_BUTTON_COUNT = 4
}
local TIC_JOYSTICKS_: type <cimport, nodecl, using> = @enum(cint){
  JOY_1 = 0,
  JOY_2 = 1,
  JOY_3 = 2,
  JOY_4 = 3,
  JOY_5 = 4,
  JOY_6 = 5,
  JOY_7 = 6,
  JOY_8 = 7,
  JOY_9 = 8,
  JOY_10 = 9,
  JOY_11 = 10,
  JOY_12 = 11,
  JOY_13 = 12,
  JOY_14 = 13,
  JOY_15 = 14,
  JOY_16 = 15,
  JOY_COUNT = 16,
  JOY_LAST = 15
}
local TIC_JOYSTICK_BUTTON_: type <cimport, nodecl, using> = @enum(cint){
  JOY_BUTTON_A = 0,
  JOY_BUTTON_B = 1,
  JOY_BUTTON_X = 2,
  JOY_BUTTON_Y = 3,
  JOY_BUTTON_LEFT_BUMPER = 4,
  JOY_BUTTON_RIGHT_BUMPER = 5,
  JOY_BUTTON_BACK = 6,
  JOY_BUTTON_START = 7,
  JOY_BUTTON_GUIDE = 8,
  JOY_BUTTON_LEFT_THUMB = 9,
  JOY_BUTTON_RIGHT_THUMB = 10,
  JOY_BUTTON_DPAD_UP = 11,
  JOY_BUTTON_DPAD_RIGHT = 12,
  JOY_BUTTON_DPAD_DOWN = 13,
  JOY_BUTTON_DPAD_LEFT = 14,
  JOY_BUTTON_COUNT = 15,
  JOY_BUTTON_LAST = 14
}
local TIC_JOYSTICK_AXES_: type <cimport, nodecl, using> = @enum(cint){
  JOY_AXIS_LEFT_X = 0,
  JOY_AXIS_LEFT_Y = 1,
  JOY_AXIS_RIGHT_X = 2,
  JOY_AXIS_RIGHT_Y = 3,
  JOY_AXIS_LEFT_TRIGGER = 4,
  JOY_AXIS_RIGHT_TRIGGER = 5,
  JOY_AXIS_COUNT = 6,
  JOY_AXIS_LAST = 5
}
local TIC_INPUT_FLAGS_: type <cimport, nodecl, using> = @enum(cint){
  INPUT_INIT_ALL = 0,
  INIT_KEYBOARD = 1,
  INIT_MOUSE = 4,
  INIT_JOYSTICK = 8
}
local tc_Input: type <cimport, nodecl> = @record{
  names: record{
    mouseButtonNames: map_int_t,
    keyNames: map_int_t,
    joyButtonNames: map_int_t,
    joyAxisNames: map_int_t
  },
  mouseState: record{
    x: cint,
    y: cint,
    fixX: cint,
    fixY: cint,
    scrollX: float32,
    scrollY: float32,
    scroll: tc_Vec2,
    scroll_delta: tc_Vec2,
    pos: tc_Vec2,
    pos_delta: tc_Vec2,
    down: [3]cint,
    pressed: [3]cint,
    fixed: cint,
    active: cint
  },
  keyState: record{
    down: [348]cint,
    pressed: [348]cint,
    active: cint
  },
  joystickState: [16]record{
    down: [15]cint,
    pressed: [15]cint,
    axis: [6]float32,
    active: cint
  }
}
function tico.input_init(input: *tc_Input, flags: TIC_INPUT_FLAGS_): cint <cimport'tico_input_init', nodecl> end
function tico.input_terminate(input: *tc_Input) <cimport'tico_input_terminate', nodecl> end
function tico.input_update(input: *tc_Input): cint <cimport'tico_input_update', nodecl> end
local tc_Config: type <cimport, nodecl> = @record{
  title: [256]cchar,
  width: cint,
  height: cint,
  flags: cint,
  window_flags: TIC_WindowFlags_,
  argc: cint,
  argv: *cstring,
  plugins: vec_str_t
}
local tc_Core: type <cimport, nodecl> = @record{
  timer: tc_Timer,
  graphics: tc_Graphics,
  window: tc_Window,
  input: tc_Input,
  fs: tc_Filesystem,
  plugins: tc_PluginModule
}
function tico.config_load(path: cstring, argc: cint, argv: *cstring): tc_Config <cimport'tico_config_load', nodecl> end
function tico.config_init(title: cstring, width: cint, height: cint, argc: cint, argv: *cstring): tc_Config <cimport'tico_config_init', nodecl> end
function tico.init(config: *tc_Config): cint <cimport'tico_init', nodecl> end
function tico.terminate() <cimport'tico_terminate', nodecl> end
function tico.poll_events() <cimport'tico_poll_events', nodecl> end
function tico.update(): cint <cimport'tico_update', nodecl> end
function tico.begin_draw(): cint <cimport'tico_begin_draw', nodecl> end
function tico.end_draw(): cint <cimport'tico_end_draw', nodecl> end
function tico.main_loop(): cint <cimport'tico_main_loop', nodecl> end
function tico.plugins_default() <cimport'tico_plugins_default', nodecl> end
function tico.plugins_enable(name: cstring) <cimport'tico_plugins_enable', nodecl> end
function tico.plugins_disable(name: cstring) <cimport'tico_plugins_disable', nodecl> end
function tico.plugins_is_active(name: cstring): boolean <cimport'tico_plugins_is_active', nodecl> end
function tico.plugins_get(name: cstring): *tc_Plugin <cimport'tico_plugins_get', nodecl> end
function tico.plugins_init() <cimport'tico_plugins_init', nodecl> end
function tico.plugins_update() <cimport'tico_plugins_update', nodecl> end
function tico.plugins_begin_draw() <cimport'tico_plugins_begin_draw', nodecl> end
function tico.plugins_draw() <cimport'tico_plugins_draw', nodecl> end
function tico.plugins_end_draw() <cimport'tico_plugins_end_draw', nodecl> end
function tico.plugins_terminate() <cimport'tico_plugins_terminate', nodecl> end
function tico.timer_update() <cimport'tico_timer_update', nodecl> end
function tico.timer_get_time(): float32 <cimport'tico_timer_get_time', nodecl> end
function tico.timer_get_delta(): float32 <cimport'tico_timer_get_delta', nodecl> end
function tico.timer_get_fps(): cint <cimport'tico_timer_get_fps', nodecl> end
function tico.timer_wait(ms: float32) <cimport'tico_timer_wait', nodecl> end
function tico.filesystem_set_packed(packed: cint) <cimport'tico_filesystem_set_packed', nodecl> end
function tico.filesystem_is_packed(): boolean <cimport'tico_filesystem_is_packed', nodecl> end
function tico.filesystem_set_path(path: cstring) <cimport'tico_filesystem_set_path', nodecl> end
function tico.filesystem_get_path(): *cuchar <cimport'tico_filesystem_get_path', nodecl> end
function tico.filesystem_resolve_path(outName: cstring, filename: cstring) <cimport'tico_filesystem_resolve_path', nodecl> end
function tico.filesystem_get_exe_path(): *cuchar <cimport'tico_filesystem_get_exe_path', nodecl> end
function tico.filesystem_read_internal_file(filename: cstring, outSize: *csize): *cuchar <cimport'tico_filesystem_read_internal_file', nodecl> end
function tico.filesystem_read_external_file(filename: cstring, outSize: *csize): *cuchar <cimport'tico_filesystem_read_external_file', nodecl> end
function tico.filesystem_write_internal_file(filename: cstring, text: cstring, size: csize, mode: TIC_WRITE_MODE_) <cimport'tico_filesystem_write_internal_file', nodecl> end
function tico.filesystem_write_external_file(filename: cstring, text: cstring, size: csize, mode: TIC_WRITE_MODE_) <cimport'tico_filesystem_write_external_file', nodecl> end
function tico.filesystem_internal_file_exists(filename: cstring): cint <cimport'tico_filesystem_internal_file_exists', nodecl> end
function tico.filesystem_external_file_exists(filename: cstring): cint <cimport'tico_filesystem_external_file_exists', nodecl> end
function tico.filesystem_read_file(filename: cstring, outSize: *csize): *cuchar <cimport'tico_filesystem_read_file', nodecl> end
function tico.filesystem_write_file(filename: cstring, text: cstring, size: csize, mode: TIC_WRITE_MODE_) <cimport'tico_filesystem_write_file', nodecl> end
function tico.filesystem_delete_file(filename: cstring) <cimport'tico_filesystem_delete_file', nodecl> end
function tico.filesystem_file_exists(filename: cstring): cint <cimport'tico_filesystem_file_exists', nodecl> end
function tico.filesystem_mkdir(path: cstring) <cimport'tico_filesystem_mkdir', nodecl> end
function tico.filesystem_rmdir(path: cstring) <cimport'tico_filesystem_rmdir', nodecl> end
function tico.graphics_draw(texture: tc_Texture, dest: tc_Rectf, source: tc_Rectf, color: tc_Color) <cimport'tico_graphics_draw', nodecl> end
function tico.graphics_draw_ex(texture: tc_Texture, dest: tc_Rectf, source: tc_Rectf, angle: float32, origin: tc_Vec2, color: tc_Color) <cimport'tico_graphics_draw_ex', nodecl> end
function tico.graphics_clear(color: tc_Color) <cimport'tico_graphics_clear', nodecl> end
function tico.graphics_push() <cimport'tico_graphics_push', nodecl> end
function tico.graphics_pop() <cimport'tico_graphics_pop', nodecl> end
function tico.graphics_origin() <cimport'tico_graphics_origin', nodecl> end
function tico.graphics_translate(x: float32, y: float32) <cimport'tico_graphics_translate', nodecl> end
function tico.graphics_rotate(angle: float32) <cimport'tico_graphics_rotate', nodecl> end
function tico.graphics_scale(x: float32, y: float32) <cimport'tico_graphics_scale', nodecl> end
function tico.graphics_scissor(x: cint, y: cint, w: cint, h: cint) <cimport'tico_graphics_scissor', nodecl> end
function tico.graphics_send(name: cstring, data: pointer, type: TIC_SHADER_UNIFORM_) <cimport'tico_graphics_send', nodecl> end
function tico.graphics_send_count(name: cstring, count: cint, data: pointer, type: TIC_SHADER_UNIFORM_) <cimport'tico_graphics_send_count', nodecl> end
function tico.graphics_default_vertex_shader(): cint <cimport'tico_graphics_default_vertex_shader', nodecl> end
function tico.graphics_default_fragment_shader(): cint <cimport'tico_graphics_default_fragment_shader', nodecl> end
function tico.graphics_default_shader(): tc_Shader <cimport'tico_graphics_default_shader', nodecl> end
function tico.graphics_push_shader(shader: tc_Shader) <cimport'tico_graphics_push_shader', nodecl> end
function tico.graphics_pop_shader() <cimport'tico_graphics_pop_shader', nodecl> end
function tico.graphics_push_canvas(canvas: tc_Canvas) <cimport'tico_graphics_push_canvas', nodecl> end
function tico.graphics_pop_canvas() <cimport'tico_graphics_pop_canvas', nodecl> end
function tico.graphics_top_canvas(): tc_Canvas <cimport'tico_graphics_top_canvas', nodecl> end
function tico.graphics_push_matrix(matrix: tc_Matrix) <cimport'tico_graphics_push_matrix', nodecl> end
function tico.graphics_pop_matrix() <cimport'tico_graphics_pop_matrix', nodecl> end
function tico.graphics_draw_rectangle(x: float32, y: float32, width: cint, height: cint, color: tc_Color) <cimport'tico_graphics_draw_rectangle', nodecl> end
function tico.graphics_fill_rectangle(x: float32, y: float32, width: float32, height: float32, color: tc_Color) <cimport'tico_graphics_fill_rectangle', nodecl> end
function tico.graphics_draw_rect(rect: tc_Rect, color: tc_Color) <cimport'tico_graphics_draw_rect', nodecl> end
function tico.graphics_fill_rect(rect: tc_Rect, color: tc_Color) <cimport'tico_graphics_fill_rect', nodecl> end
function tico.graphics_draw_circle(x: cint, y: cint, radius: float32, color: tc_Color) <cimport'tico_graphics_draw_circle', nodecl> end
function tico.graphics_fill_circle(x: cint, y: cint, radius: float32, color: tc_Color) <cimport'tico_graphics_fill_circle', nodecl> end
function tico.graphics_draw_circle_ex(x: cint, y: cint, radius: float32, sides: cint, color: tc_Color) <cimport'tico_graphics_draw_circle_ex', nodecl> end
function tico.graphics_fill_circle_ex(x: cint, y: cint, radius: float32, sides: cint, color: tc_Color) <cimport'tico_graphics_fill_circle_ex', nodecl> end
function tico.graphics_draw_triangle(x0: cint, y0: cint, x1: cint, y1: cint, x2: cint, y2: cint, color: tc_Color) <cimport'tico_graphics_draw_triangle', nodecl> end
function tico.graphics_fill_triangle(x0: cint, y0: cint, x1: cint, y1: cint, x2: cint, y2: cint, color: tc_Color) <cimport'tico_graphics_fill_triangle', nodecl> end
function tico.graphics_draw_line(x0: cint, y0: cint, x1: cint, y1: cint, color: tc_Color) <cimport'tico_graphics_draw_line', nodecl> end
function tico.graphics_draw_text(text: cstring, x: cint, y: cint, color: tc_Color) <cimport'tico_graphics_draw_text', nodecl> end
function tico.graphics_draw_text_scale(text: cstring, x: cint, y: cint, sx: float32, sy: float32, color: tc_Color) <cimport'tico_graphics_draw_text_scale', nodecl> end
function tico.graphics_draw_text_ex(text: cstring, x: cint, y: cint, angle: float32, sx: float32, sy: float32, cx: cint, cy: cint, color: tc_Color) <cimport'tico_graphics_draw_text_ex', nodecl> end
function tico.graphics_draw_text_font(font: tc_Font, text: cstring, x: cint, y: cint, color: tc_Color) <cimport'tico_graphics_draw_text_font', nodecl> end
function tico.graphics_draw_text_font_scale(font: tc_Font, text: cstring, x: cint, y: cint, sx: float32, sy: float32, color: tc_Color) <cimport'tico_graphics_draw_text_font_scale', nodecl> end
function tico.graphics_draw_text_font_ex(font: tc_Font, text: cstring, x: cint, y: cint, angle: float32, sx: float32, sy: float32, cx: cint, cy: cint, color: tc_Color) <cimport'tico_graphics_draw_text_font_ex', nodecl> end
function tico.graphics_draw_text_font_scale_width(font: tc_Font, text: cstring, x: cint, y: cint, width: cint, sx: float32, sy: float32, color: tc_Color) <cimport'tico_graphics_draw_text_font_scale_width', nodecl> end
function tico.input_update_mouse_scroll(x: float32, y: float32) <cimport'tico_input_update_mouse_scroll', nodecl> end
function tico.input_update_key(key: TIC_KEY_, action: cint) <cimport'tico_input_update_key', nodecl> end
function tico.input_update_mouse_pos(x: cint, y: cint) <cimport'tico_input_update_mouse_pos', nodecl> end
function tico.input_update_joy_button(jid: TIC_JOYSTICKS_, button: TIC_JOYSTICK_BUTTON_, action: cint) <cimport'tico_input_update_joy_button', nodecl> end
function tico.input_update_mouse_button(button: TIC_MOUSEBUTTON_, action: cint) <cimport'tico_input_update_mouse_button', nodecl> end
function tico.input_get_key_code(name: cstring): cint <cimport'tico_input_get_key_code', nodecl> end
function tico.input_get_joy_btncode(name: cstring): cint <cimport'tico_input_get_joy_btncode', nodecl> end
function tico.input_get_joy_axiscode(name: cstring): cint <cimport'tico_input_get_joy_axiscode', nodecl> end
function tico.input_get_mouse_code(name: cstring): cint <cimport'tico_input_get_mouse_code', nodecl> end
function tico.input_key_down(key: TIC_KEY_): boolean <cimport'tico_input_key_down', nodecl> end
function tico.input_key_pressed(key: TIC_KEY_): boolean <cimport'tico_input_key_pressed', nodecl> end
function tico.input_key_up(key: TIC_KEY_): boolean <cimport'tico_input_key_up', nodecl> end
function tico.input_key_released(key: TIC_KEY_): boolean <cimport'tico_input_key_released', nodecl> end
function tico.input_mouse_down(button: TIC_MOUSEBUTTON_): boolean <cimport'tico_input_mouse_down', nodecl> end
function tico.input_mouse_pressed(button: TIC_MOUSEBUTTON_): boolean <cimport'tico_input_mouse_pressed', nodecl> end
function tico.input_mouse_up(button: TIC_MOUSEBUTTON_): boolean <cimport'tico_input_mouse_up', nodecl> end
function tico.input_mouse_released(button: TIC_MOUSEBUTTON_): boolean <cimport'tico_input_mouse_released', nodecl> end
function tico.input_mouse_set_cursor(cursor: cint) <cimport'tico_input_mouse_set_cursor', nodecl> end
function tico.input_joy_down(jid: TIC_JOYSTICKS_, button: TIC_JOYSTICK_BUTTON_): boolean <cimport'tico_input_joy_down', nodecl> end
function tico.input_joy_up(jid: TIC_JOYSTICKS_, button: TIC_JOYSTICK_BUTTON_): boolean <cimport'tico_input_joy_up', nodecl> end
function tico.input_joy_pressed(jid: TIC_JOYSTICKS_, button: TIC_JOYSTICK_BUTTON_): boolean <cimport'tico_input_joy_pressed', nodecl> end
function tico.input_joy_released(jid: TIC_JOYSTICKS_, button: TIC_JOYSTICK_BUTTON_): boolean <cimport'tico_input_joy_released', nodecl> end
function tico.input_get_mouse_pos(x: *cint, y: *cint) <cimport'tico_input_get_mouse_pos', nodecl> end
function tico.input_fix_mouse() <cimport'tico_input_fix_mouse', nodecl> end
function tico.input_release_mouse() <cimport'tico_input_release_mouse', nodecl> end
function tico.input_get_mouse_delta(x: *cint, y: *cint) <cimport'tico_input_get_mouse_delta', nodecl> end
function tico.input_get_mouse_scroll(x: *float32, y: *float32) <cimport'tico_input_get_mouse_scroll', nodecl> end
function tico.input_get_mouse_scroll_delta(x: *float32, y: *float32) <cimport'tico_input_get_mouse_scroll_delta', nodecl> end
function tico.window_should_close(): boolean <cimport'tico_window_should_close', nodecl> end
function tico.window_swap_buffers() <cimport'tico_window_swap_buffers', nodecl> end
function tico.window_get_pos(x: *cint, y: *cint) <cimport'tico_window_get_pos', nodecl> end
function tico.window_set_pos(x: cint, y: cint) <cimport'tico_window_set_pos', nodecl> end
function tico.window_get_width(): cint <cimport'tico_window_get_width', nodecl> end
function tico.window_set_width(width: cint) <cimport'tico_window_set_width', nodecl> end
function tico.window_get_height(): cint <cimport'tico_window_get_height', nodecl> end
function tico.window_set_height(height: cint) <cimport'tico_window_set_height', nodecl> end
function tico.window_get_size(width: *cint, height: *cint) <cimport'tico_window_get_size', nodecl> end
function tico.window_set_size(width: cint, height: cint) <cimport'tico_window_set_size', nodecl> end
function tico.window_get_title(): cstring <cimport'tico_window_get_title', nodecl> end
function tico.window_set_title(title: cstring) <cimport'tico_window_set_title', nodecl> end
function tico.window_is_fullscreen(): boolean <cimport'tico_window_is_fullscreen', nodecl> end
function tico.window_set_fullscreen(fullscreen: cint) <cimport'tico_window_set_fullscreen', nodecl> end
function tico.window_toggle_fullscreen() <cimport'tico_window_toggle_fullscreen', nodecl> end
function tico.window_is_resizable(): boolean <cimport'tico_window_is_resizable', nodecl> end
function tico.window_set_resizable(resizable: cint) <cimport'tico_window_set_resizable', nodecl> end
function tico.window_toggle_resizable() <cimport'tico_window_toggle_resizable', nodecl> end
function tico.window_get_vsync(): cint <cimport'tico_window_get_vsync', nodecl> end
function tico.window_set_vsync(vsync: cint) <cimport'tico_window_set_vsync', nodecl> end
function tico.plugin_add_plugin(name: cstring, plugin: tc_Plugin) <cimport'tico_plugin_add_plugin', nodecl> end
function tico.plugin_enable_plugin(name: cstring) <cimport'tico_plugin_enable_plugin', nodecl> end
function tico.plugin_disable_plugin(name: cstring) <cimport'tico_plugin_disable_plugin', nodecl> end
function tico.plugin_is_active(name: cstring): boolean <cimport'tico_plugin_is_active', nodecl> end
function tico.plugin_get(name: cstring): *tc_Plugin <cimport'tico_plugin_get', nodecl> end
function tico.plugin_module_init(): cint <cimport'tico_plugin_module_init', nodecl> end
function tico.plugin_module_terminate() <cimport'tico_plugin_module_terminate', nodecl> end
function tico.plugin_module_update() <cimport'tico_plugin_module_update', nodecl> end
function tico.plugin_module_begin_draw() <cimport'tico_plugin_module_begin_draw', nodecl> end
function tico.plugin_module_draw() <cimport'tico_plugin_module_draw', nodecl> end
function tico.plugin_module_end_draw() <cimport'tico_plugin_module_end_draw', nodecl> end

-- export records
global tico.Tileset: type = @tc_Tileset
global tico.Tilemap: type = @tc_Tilemap
global tico.Camera: type = @tc_Camera
global tico.Animation: type = @tc_Animation
global tico.Sprite: type = @tc_Sprite
global tico.Timer: type = @tc_Timer
global tico.Plugin: type = @tc_Plugin
global tico.PluginModule: type = @tc_PluginModule
global tico.Lua: type = @tc_Lua
global tico.ResourceDep: type = @tc_ResourceDep
global tico.Resource: type = @tc_Resource
global tico.ResourcePlugin: type = @tc_ResourcePlugin
global tico.ResourceManager: type = @tc_ResourceManager
global tico.PanelWidget: type = @tc_PanelWidget
global tico.GridWidget: type = @tc_GridWidget
global tico.Object: type = @tc_Object
global tico.ObjectWidget: type = @tc_ObjectWidget
global tico.GridTool: type = @tc_GridTool
global tico.EditorFolder: type = @tc_EditorFolder
global tico.EditorPlugin: type = @tc_EditorPlugin
global tico.EditorWindow: type = @tc_EditorWindow
global tico.Editor: type = @tc_Editor
global tico.AudioData: type = @tc_AudioData
global tico.AudioBuffer: type = @tc_AudioBuffer
global tico.Sound: type = @tc_Sound
global tico.Vertex: type = @tc_Vertex
global tico.DrawCall: type = @tc_DrawCall
global tico.Batch: type = @tc_Batch
global tico.Render: type = @tc_Render
global tico.Graphics: type = @tc_Graphics
global tico.Window: type = @tc_Window
global tico.Input: type = @tc_Input
global tico.Config: type = @tc_Config
global tico.Core: type = @tc_Core
global tico.Rect: type = @tc_Rect
global tico.Rectf: type = @tc_Rectf
global tico.Circle: type = @tc_Circle
global tico.Circlef: type = @tc_Circlef
global tico.Color: type = @tc_Color
global tico.Texture: type = @tc_Texture
global tico.Image: type = @tc_Image
global tico.Canvas: type = @tc_Canvas
global tico.Shader: type = @tc_Shader
global tico.CharacterInfo: type = @tc_CharacterInfo
global tico.Font: type = @tc_Font
global tico.Vec2: type = @tc_Vec2
global tico.Vec3: type = @tc_Vec3
global tico.Vec4: type = @tc_Vec4
global tico.Matrix: type = @tc_Matrix
global tico.Filesystem: type = @tc_Filesystem
global tico.MetaFn: type = @tc_MetaFn
global tico.FieldFn: type = @tc_FieldFn
global tico.FieldType: type = @tc_FieldType
global tico.Serialization: type = @tc_Serialization
global tico.Field: type = @tc_Field
global tico.Meta: type = @tc_Meta

-- export enums
global tico.FIELD_TYPE = TIC_FIELD_TYPE_
global tico.AUDIO_USAGE = TIC_AUDIO_USAGE_
global tico.DRAW_MODE = TIC_DRAW_MODE_
global tico.FRAGMENT_SHADERS = TIC_FRAGMENT_SHADERS_
global tico.VERTEX_SHADERS = TIC_VERTEX_SHADERS_
global tico.WindowFlags = TIC_WindowFlags_
global tico.KEY = TIC_KEY_
global tico.MOUSEBUTTON = TIC_MOUSEBUTTON_
global tico.JOYSTICKS = TIC_JOYSTICKS_
global tico.JOYSTICK_BUTTON = TIC_JOYSTICK_BUTTON_
global tico.JOYSTICK_AXES = TIC_JOYSTICK_AXES_
global tico.INPUT_FLAGS = TIC_INPUT_FLAGS_
global tico.SHADER_UNIFORM = TIC_SHADER_UNIFORM_
global tico.FILE_TYPE = TIC_FILE_TYPE_
global tico.WRITE_MODE = TIC_WRITE_MODE_

-- export constants
global tico.RESOURCE_ERROR = TIC_RESOURCE_ERROR
global tico.RESOURCE_LOADED = TIC_RESOURCE_LOADED
global tico.RESOURCE_MISSING_DEP = TIC_RESOURCE_MISSING_DEP
global tico.RESOURCE_CHANGED = TIC_RESOURCE_CHANGED

global tico.CURSOR_ARROW = TIC_CURSOR_ARROW
global tico.CURSOR_TEXT = TIC_CURSOR_TEXT
global tico.CURSOR_CROSSHAIR = TIC_CURSOR_CROSSHAIR
global tico.CURSOR_HAND = TIC_CURSOR_HAND
global tico.CURSOR_HRESIZE = TIC_CURSOR_HRESIZE
global tico.CURSOR_VRESIZE = TIC_CURSOR_VRESIZE

-- create color palette with the same values as the original ones
global tico.WHITE: tc_Color <const> = { 255, 255, 255, 255 }
global tico.BLACK: tc_Color <const> = {   0,   0,   0, 255 }
global tico.BLUE : tc_Color <const> = {  48,  52, 109, 255 }
global tico.RED  : tc_Color <const> = { 208,  70,  72, 255 }
global tico.GREEN: tc_Color <const> = {  52, 101,  36, 255 }
global tico.GRAY : tc_Color <const> = {  78,  74,  78, 255 }
global tico.BROWN: tc_Color <const> = { 133,  76,  48, 255 }
global tico.BG   : tc_Color <const> = {  75,  90,  90, 255 }



-- apply operator overloading
function tc_Vec2.__eq(a: tc_Vec2, b: tc_Vec2): boolean <cimport'tico_vec2_equals', nodecl> end
function tc_Vec2.__len(v: tc_Vec2): float32 <cimport'tico_vec2_len', nodecl> end
function tc_Vec2.__add(a: tc_Vec2, b: tc_Vec2): tc_Vec2 <inline> tico.vec2_add(&a, a, b) return a end
function tc_Vec2.__sub(a: tc_Vec2, b: tc_Vec2): tc_Vec2 <inline> tico.vec2_sub(&a, a, b) return a end
function tc_Vec2.__mul(a: tc_Vec2, n: float32): tc_Vec2 <inline> tico.vec2_mul(&a, a, n) return a end
function tc_Vec2.__div(a: tc_Vec2, n: float32): tc_Vec2 <inline> tico.vec2_div(&a, a, n) return a end

function tc_Vec3.__eq(a: tc_Vec3, b: tc_Vec3): boolean <cimport'tico_vec3_equals', nodecl> end
function tc_Vec3.__len(v: tc_Vec3): float32 <cimport'tico_vec3_len', nodecl> end
function tc_Vec3.__add(a: tc_Vec3, b: tc_Vec3): tc_Vec3 <inline> tico.vec3_add(&a, a, b) return a end
function tc_Vec3.__sub(a: tc_Vec3, b: tc_Vec3): tc_Vec3 <inline> tico.vec3_sub(&a, a, b) return a end
function tc_Vec3.__mul(a: tc_Vec3, n: float32): tc_Vec3 <inline> tico.vec3_mul(&a, a, n) return a end
function tc_Vec3.__div(a: tc_Vec3, n: float32): tc_Vec3 <inline> tico.vec3_div(&a, a, n) return a end

function tc_Vec4.__eq(a: tc_Vec4, b: tc_Vec4): boolean <cimport'tico_vec4_equals', nodecl> end
function tc_Vec4.__len(v: tc_Vec4): float32 <cimport'tico_vec4_len', nodecl> end
function tc_Vec4.__add(a: tc_Vec4, b: tc_Vec4): tc_Vec4 <inline> tico.vec4_add(&a, a, b) return a end
function tc_Vec4.__sub(a: tc_Vec4, b: tc_Vec4): tc_Vec4 <inline> tico.vec4_sub(&a, a, b) return a end
function tc_Vec4.__mul(a: tc_Vec4, n: float32): tc_Vec4 <inline> tico.vec4_mul(&a, a, n) return a end
function tc_Vec4.__div(a: tc_Vec4, n: float32): tc_Vec4 <inline> tico.vec4_div(&a, a, n) return a end
