-- minimal example of a box falling --

--[[
  Copyright (c) 2020-present André Luiz Alvares

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at https://mozilla.org/MPL/2.0/.

  SPDX-License-Identifier: MPL-2.0
]]

-- nene
local Nene = require 'nene.core'
local Color = require 'nene.color'

-- rotor
local entity = require 'rotor.entity'
local storage = require 'rotor.storage'
local system = require 'rotor.system'

-- irene
local Painter = require 'irene.components.painter'
local Position = require 'irene.components.position'
local Gravity = require 'irene.components.gravity'
local Velocity = require 'irene.components.velocity'
local RectPainter = require 'irene.components.rect_painter'

local GravitySystem = require 'irene.systems.gravity_system'
local VelocitySystem = require 'irene.systems.velocity_system'
local RectPainterSystem = require 'irene.systems.rect_painter_system'

-- Falling box entity
local FallingBox <nickname 'FallingBox'> = @entity(record{
  position: Position,

  gravity: Gravity,
  velocity: Velocity,

  painter: Painter,
  rect_painter: RectPainter,
})

-- systems
local gravity_system: system(GravitySystem.run)
local velocity_system: system(VelocitySystem.run)
local rect_painter_system: system(RectPainterSystem.run)

-- basic gravity --
local box: FallingBox = {
  position = {
    local_pos = {-8, 48},
  },

  velocity = {
    active = true,
    use_deltatime = true,
  },

  gravity = {
    active = true,
    acceleration = 10,
    direction = { 0, -1 },
  },

  painter = {
    active = true,
  },

  rect_painter = {
    size = { 16, 16 },
    color = Color.yellow,
  },
}

local ok = Nene.init('Irene - Basic gravity', 256, 256)
assert(ok, 'error: nene initialization failed.')

repeat
  Nene.update()

  gravity_system:run(&box)
  velocity_system:run(&box)

  Nene.render_clear(Color.bg)

  rect_painter_system:run(&box)

  Nene.render_present()
until Nene.should_quit()
