-- bench test --
-- this is a port of rotor's bench example.

--[[
  Copyright (c) 2020-2022 André Luiz Alvares

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at https://mozilla.org/MPL/2.0/.

  SPDX-License-Identifier: MPL-2.0
]]

-- nelua
local math = require 'math'

-- nene
local Nene = require 'nene'
local Color = require 'nene.color'

-- rotor
local storage   = require 'rotor.storage'
local entity    = require 'rotor.entity'
local system    = require 'rotor.system'
local GenIdx    = require 'rotor.gen_idx'

-- irene
local Position = require 'irene.components.position'
local Velocity = require 'irene.components.velocity'
local EntityData = require 'irene.components.entity_data'
local RectPainter = require 'irene.components.rect_painter'
local Painter = require 'irene.components.painter'

local VelocitySystem = require 'irene.systems.velocity_system'
local RectPainterSystem = require 'irene.systems.rect_painter_system'

-- bench
local e_count = 0_u
local E_COUNT <comptime> = #[ E_COUNT or 5000 ]#
local E_DELTA <comptime> = #[ E_DELTA or 100 ]#

local ok, nene <close> = Nene.init('Irene port of Rotor Benchmark', 800, 600)
assert(ok, 'error: nene initialization failed.')

local Particle <nickname 'Particle'> = @entity(record{
  position: Position,
  velocity: Velocity,
  painter: Painter,
  rect_painter: RectPainter,
  entity_data: EntityData,
})

local Particle.storage: storage(Particle, E_COUNT)

function Particle.init(): Particle
  local particle: Particle = {
    velocity = {
      active = true,
      final_velocity = {
        math.random(25, 50), math.random(25, 50)
      },
      use_deltatime = true,
    },

    painter = {
      active = true,
      use_tint = true,
      tint = Color.Palette.yellow,
    },
    
    rect_painter = {
      size = { 2, 2 },
    }
  }
  return particle
end

function Particle.spawn()
  local ok, id, particle = Particle.storage:push(Particle.init())
  assert(ok, "The particle couldn't be pushed to storage")

  particle.entity_data.id = id
  e_count = e_count + 1

  ## if not NOLOG then
    print('SPAWN: ', id.index, id.generation)
  ## end
end

function Particle.remove(id: GenIdx)
  Particle.storage:remove(id)
  e_count = e_count - 1

  ## if not NOLOG then
    print('DEAD: ', id.index, id.generation)
  ## end
end

local CycleOrDestroySystem = @record{}
local CycleOrDestroySystem.Filter = @record{ position: *Position, entity_data: *EntityData }

function CycleOrDestroySystem:run(e: CycleOrDestroySystem.Filter)
  local pos = e.position:final_pos()

  if pos.x > 800 or pos.y > 600 then
    if math.random() < 0.4 then
      Particle.remove(e.entity_data.id)
    else
      e.position.local_pos.x, e.position.local_pos.y = 0, 0
    end
  end
end

local velocity_system: system(VelocitySystem.run)
local rect_painter_system: system(RectPainterSystem.run)
local cycle_or_destroy_system: system(CycleOrDestroySystem.run)

local function frame()
  nene:poll_events()

  for i = 1, E_DELTA do
    if e_count < E_COUNT then
      Particle.spawn()
    end
  end

  velocity_system:run(&Particle.storage)
  cycle_or_destroy_system:run(&Particle.storage)

  nene:render_clear(Color.Palette.bg)

  do
    ## if not NODRAW then
      rect_painter_system:run(&Particle.storage)
    ## end

    ## if not NOFPS then
      print('dt: ', nene.delta_time)
    ## end

    ## if not NODRAWCOUNT then
      print('e_count: ', e_count)
    ## end
  end

  nene:render_present()
end

repeat
  frame()
until nene.quit
