--[[
  Copyright (c) 2020-present André Luiz Alvares

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at https://mozilla.org/MPL/2.0/.

  SPDX-License-Identifier: MPL-2.0
]]

local EntityMask = @enum(byte){
  Lander = 0b001,
  Floor  = 0b010,
  Safe   = 0b100,
}

return EntityMask
