require 'math'
require 'nene'
require 'rotor.optional'
require 'rotor-quick.makers'

global RotorQuick.Components.CameraHolder = @record{
  camera: Nene.Camera
}

local CameraHolder = RotorQuick.Components.CameraHolder

## is_component(CameraHolder)

function CameraHolder:set_target(target: GameMath.Vec2)
  target.x = -target.x
  target.y = -target.y

  --tico.camera_set_pos(self.camera, target)
end
