require 'tico'
require 'math'
require 'rotor.optional'
require 'rotor-quick.makers'

local Vec2 = tico.Vec2
local Camera = tico.Camera

global RotorQuick.Components.CameraHolder = @record{
  camera: Camera
}

local CameraHolder = RotorQuick.Components.CameraHolder

## is_component(CameraHolder)

function CameraHolder:set_target(target: Vec2)
  target.x = -target.x
  target.y = -target.y

  tico.camera_set_pos(self.camera, target)
end
