require 'vector'
require 'nene.math'
require 'rotor-quick.makers'

local ShapeCategory = @enum{
  Rectangle = 1,
  Circle,
  Triangle,
  Polygon
}

global RotorQuick.Components.Shape = @record{
  category: ShapeCategory,
  vertices: vector(Nene.Math.Vec2), -- TODO: rethink this type, can be optimized?
}

local Shape = RotorQuick.Components.Shape
## is_component(Shape)

global Shape.ShapeCategory = ShapeCategory
