global RotorQuick.Systems = @record{}

require 'rotor-quick.systems.gravity_applier'
require 'rotor-quick.systems.shape_painter'
require 'rotor-quick.systems.velocity_applier'
require 'rotor-quick.systems.intersectable_update'
require 'rotor-quick.systems.intersectable_painter'
require 'rotor-quick.systems.intersections_detector'
require 'rotor-quick.systems.intersections_painter'
require 'rotor-quick.systems.sprite_painter'
