--[[
  Copyright (c) 2020-present André Luiz Alvares

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at https://mozilla.org/MPL/2.0/.

  SPDX-License-Identifier: MPL-2.0
]]

--[ dependencies ]--
-- nene
local Vec2i = require 'nene.math.vec2i'

--[ Settings ]--
local Settings = @record{}

local Settings.WINDOW_WIDTH <comptime> = 800
local Settings.WINDOW_HEIGHT <comptime> = 624

local Settings.SCREEN_WIDTH <comptime> = (Settings.WINDOW_WIDTH // 2)
local Settings.SCREEN_HEIGHT <comptime> = (Settings.WINDOW_HEIGHT // 2)

local Settings.TILE_SIZE: Vec2i <const>  = { 16, 16 }
local Settings.BG_TILE_SIZE: Vec2i <const>  = { 32, 32 }

return Settings
